.gitignore, frontoffice/urls.py
@htmfilho 
Je dois tester si cela fonctionne en dev.
Ensuite je remettrai la config de dev pour prendre en compte les deux modules , et ne les retirerai que de prod. Ces opération ne demanderons pas de merge supplémentaires (c'est au niveau des fichier de config serveurs)
=> #157 inclusion d'un fichier urls propre au serveurs

doc/technical-manual.adoc
git@github.com:uclouvain/osis.git --> git@github.com:uclouvain/osis-portal.git
=> Correction adresse dépôt osis-portal

frontoffice/settings.py
Inform the ticket you are solving in this pull request: #219
=> #219 suppression import servers_apps

performance/models/student_performance.py
Inform the ticket you are solving in this pull request: #224 
- [ x] it contains only **well formatted** code, using **4 spaces** for identation and a maximum of **120 characters** per line.
- [ x] classes, methods or function names are **not abreviated**.
- [ x] the code seems **readable for other developers** who will maintain this code in the future.
- [ x] in case complexity is needed, then the code is very **well documented**.
- [ x] all files contain the **license header**.
=> fixed error when bcket not found

admission/views/identification.py
Inform the ticket you are solving in this pull request: #177
=> #177 ajout template login maquant

base/models/signals.py
Inform the ticket you are solving in this pull request: #177
=> #177 ajout verif si student.person est lié à user'

dissertation/locale/en/LC_MESSAGES/django.po, dissertation/locale/fr_BE/LC_MESSAGES/django.po, dissertation/templates/dissertation.html, dissertation/urls.py, dissertation/views/common.py
=> #238 Création du template d'accueil et implémentation de celui-ci

frontoffice/settings.py
Inform the ticket you are solving in this pull request: #51 
=> #51 modification su settings

base/models/student.py
=> #257 ajout de registration_id fans champ de recherche

base/apps.py
Inform the ticket you are solving in this pull request: #256 
=> Feature/256 Fixed bug where two persons with same global_id where created

frontoffice/queue/callbacks.py
Inform the ticket you are solving in this pull request: #268 
=> #268 mapping dans callback

performance/static/js/performance_result.js
Inform the ticket you are solving in this pull request: #264 
=> Les charactères html sont gérés dans l'affichage de perfomance

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/admin/data.html, base/templates/layout.html, base/urls.py, base/views/administration.py, dashboard/templates/dashboard.html, frontoffice/settings.py, frontoffice/urls.py, performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po, performance/templates/performance_home.html, performance/templates/performance_result.html
Inform the ticket you are solving in this pull request: #253 
=> #235 ajout administration et breadcrumb

frontoffice/queue/queue.py, frontoffice/queue/queue_actions.py
Inform the ticket you are solving in this pull request: #252 
=> #282 modif print en logger

admission/locale/en/LC_MESSAGES/django.po, admission/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #287
=> #287 suppression de la traduction dans admission

base/apps.py, base/models/person.py, base/models/student.py, base/models/tutor.py
Inform the ticket you are solving in this pull request: #289 
=> #289 modif ecoute queue person tutor student

base/models/person.py
=> #feature/289 correction erreur dans admin person

base/models/person.py, frontoffice/settings.py
Inform the ticket you are solving in this pull request: #289 
=> #289 modif logger et get_by_natural_key pour person

base/apps.py
Inform the ticket you are solving in this pull request: #289 
=> #289 erreur exception to string

base/apps.py, base/models/person.py
Inform the ticket you are solving in this pull request: #289 
=> #289 modif logging

frontoffice/settings.py
Inform the ticket you are solving in this pull request: #120
=> #120 Ajout dans les settings de ckeditor

requirements.txt
Inform the ticket you are solving in this pull request: #180
=> #180 Added dependency django-ckeditor==5.0.3

performance/static/js/performance_result.js, performance/templates/performance_home.html, performance/templates/performance_result.html
Inform the ticket you are solving in this pull request: #335 
=> corrected templates for performance

performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po, performance/templates/performance_home.html
Inform the ticket you are solving in this pull request: #335 
=> refactoring template performance

performance/forms.py
Inform the ticket you are solving in this pull request: #254 
=> #254 modif champ registration_id dans form : char not integer

performance/models/student_performance.py
Inform the ticket you are solving in this pull request: #357 
=> #357 modif methode insert/update dans couchbase

admission/migrations/0006_offeryear_offer.py, admission/models/offer_year.py
Inform the ticket you are solving in this pull request: #326 
=> #326 Correction des attributs de Offer dans Offer_year

admission/migrations/0006_offeryear_offer.py
Inform the ticket you are solving in this pull request: #326
=> #326 Removed unecessary migration

admission/utils/send_mail.py, frontoffice/settings.py
Inform the ticket you are solving in this pull request: #365 
=> #365 modification receiver mail suivant environnement

admission/utils/send_mail.py, frontoffice/settings.py
Inform the ticket you are solving in this pull request: #365 
=> #365 modif settings

admission/templates/registration/identification_forms.html
Inform the ticket you are solving in this pull request: #316 
=> #316 Fixed identation issue

admission/models/offer_year.py
=> #397 Ajout de offer dans l'admin de offer_year

admission/templates/application_layout.html, base/static/js/osis-portal.js
Inform the ticket you are solving in this pull request: #62
=> #62 Correction au niveau de la validation des assimilation

admission/templates/diploma.html, admission/views/secondary_education.py, admission/views/upload_file.py
Inform the ticket you are solving in this pull request: #36
=> #36 ok quand on clique sur le bouton sauvegarder

admission/templates/application_layout.html, admission/templates/profile.html, admission/views/common.py
Inform the ticket you are solving in this pull request: #22
=> #22 Corrections diverses

admission/templates/application_layout.html, admission/views/common.py
Inform the ticket you are solving in this pull request: #22
=> Feature/22 - Pas de preview pour les fichier d'un type autre que image

admission/templates/application_layout.html, admission/templates/diploma/professional_exam.html, admission/views/common.py, admission/views/demande_validation.py, admission/views/secondary_education.py, admission/views/upload_file.py, base/static/js/diploma.js
Inform the ticket you are solving in this pull request: #62
=> #62 Modifications diverses

admission/locale/en/LC_MESSAGES/django.po, admission/locale/fr_BE/LC_MESSAGES/django.po, admission/views/demande_validation.py
Inform the ticket you are solving in this pull request: #36
=> #36 Pour corriger le problème rencontré par Hang

base/fixtures/groups.json
Inform the ticket you are solving in this pull request: #440 
=> #440 fixture de creation et configurations des groups

frontoffice/queue/callbacks.py
Inform the ticket you are solving in this pull request: #441
=> #441 AssertionError caught in case an object to delete doesn't exist

.gitignore, admission/fixtures/profession.json, admission/forms.py, admission/locale/en/LC_MESSAGES/django.po, admission/locale/fr_BE/LC_MESSAGES/django.po, admission/templates/sociological.html, performance/models/student_performance.py
Reverts uclouvain/osis-portal#421
=> Revert "Feature/52"

admission/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #447
=> #447 Petite erreur de français bachelierr corrigée

admission/models/application.py
Inform the ticket you are solving in this pull request: #36
=> Correction shadowing

admission/views/common.py
Inform the ticket you are solving in this pull request: #377
=> L'adresse de contact n'était pas supprimée

reference/models/domain.py
Inform the ticket you are solving in this pull request: #452
=> #452 Modification de la condition pour la sélection des domaines

admission/templates/application_layout.html, admission/templates/demande_layout.html, admission/views/application.py, admission/views/offer.py, base/models/offer_year.py, base/models/offer_year_domain.py, base/static/js/osis-portal.js
Inform the ticket you are solving in this pull request: #452
=> Adaptation de la recherche des offres

admission/models/application_document_file.py, admission/templates/attachments.html, admission/views/attachments.py, admission/views/upload_file.py, base/static/js/attachments.js
Reverts uclouvain/osis-portal#498
=> Revert "Feature/212"

doc/technical-manual.adoc
Inform the ticket you are solving in this pull request: #509 
=> #509 ajout groups

admission/migrations/0009_auto_20161109_2052.py
Inform the ticket you are solving in this pull request: #478
=> Fixed migration sequence.

frontoffice/settings.py
Inform the ticket you are solving in this pull request: #524 
=> #524 maj pour osis_common 0.6

dissertation/views/proposition_dissertation.py
=> #456 Correction du bug en cas de Max student user à Zéro

dissertation/admin.py, dissertation/models/proposition_offer.py
Inform the ticket you are solving in this pull request: #516 
=> Ajout de la class PropositionOfferAdmin

dissertation/templates/dissertation.html
Inform the ticket you are solving in this pull request: #530 
=> #530 Modification de l'extend layout

admission/models/applicant_document_file.py, admission/views/common.py, admission/views/demande_validation.py, admission/views/secondary_education.py, admission/views/upload_file.py
Inform the ticket you are solving in this pull request: #50 
=> #50 modif nom fonction mal nommée + var mal nommées

base/static/js/osis-portal.js
Inform the ticket you are solving in this pull request: #34 
=> #34 Correction lien suivant demande analyste

dissertation/models/proposition_offer.py
Inform the ticket you are solving in this pull request: #518 
=> Issue#518 Masquer les sujets quand hors de la plage de dates

dissertation/views/dissertation.py
Inform the ticket you are solving in this pull request: #523 
=> Issue#523 Corrections ajout/suppression reader

dissertation/admin.py, dissertation/models/dissertation.py, dissertation/models/dissertation_document_file.py, dissertation/models/dissertation_location.py, dissertation/models/dissertation_role.py, dissertation/models/dissertation_update.py, dissertation/models/offer_proposition.py, dissertation/models/proposition_dissertation.py, dissertation/models/proposition_document_file.py, dissertation/models/proposition_role.py
Inform the ticket you are solving in this pull request: #484 
=> issue#484 Ajout raw_id_fields + admin models

requirements.txt
Inform the ticket you are solving in this pull request: #593 
=> #593 maj psycopg2 (Merge to Dev)

base/models/signals.py, base/tests/models/__init__.py, base/tests/models/test_signals.py, frontoffice/settings.py, requirements.txt
Inform the ticket you are solving in this pull request: #593 
=> Feature/593 (Merge to Qa)

base/models/signals.py, reference/migrations/0002_delete_assimilationcriteria.py
Inform the ticket you are solving in this pull request: #602 
=> Bugfix/602 (Merge to Dev)

base/models/signals.py
Inform the ticket you are solving in this pull request: #602 
=> #602 person.save si utilisateur créé, person super(save) sinon (Merge to Qa)

attribution/__init__.py, attribution/admin.py, attribution/apps.py, attribution/models/__init__.py, attribution/tests/__init__.py, attribution/views/__init__.py, frontoffice/settings.py
Inform the ticket you are solving in this pull request: #608
=> Created the module attribution

frontoffice/wsgi.py
=> Modif ref osis common

.github/PULL_REQUEST_TEMPLATE.md, frontoffice/settings.py
Inform the ticket you are solving in this pull request: #629
=> Removed comments from the QUEUE config

dissertation/admin.py, dissertation/models/adviser.py, dissertation/models/dissertation.py, dissertation/models/dissertation_document_file.py, dissertation/models/dissertation_group.py, dissertation/models/dissertation_location.py, dissertation/models/dissertation_role.py, dissertation/models/dissertation_update.py, dissertation/models/offer_proposition.py, dissertation/models/proposition_dissertation.py, dissertation/models/proposition_document_file.py, dissertation/models/proposition_offer.py, dissertation/models/proposition_role.py
Inform the ticket you are solving in this pull request: #649
=> #649 Modification d'administration To QA

frontoffice/settings.py, frontoffice/wsgi.py, performance/models/student_performance.py, performance/queue/student_performance.py
Inform the ticket you are solving in this pull request: #658
=> Modif queue et recherche donnée

performance/queue/student_performance.py
Inform the ticket you are solving in this pull request: #658
=> #658 modif lors de re eption notes

doc/technical-manual.adoc, frontoffice/settings.py, requirements.txt
Inform the ticket you are solving in this pull request: #667
=> #667 supression pour deploiement local

frontoffice/settings.py
=> #624 Modif settings

dashboard/tests/ressources/score_encoding_sample.json, dashboard/tests/views/test_main.py, dashboard/tests/views/test_score_encoding.py, dashboard/views/score_encoding.py
Inform the ticket you are solving in this pull request: #661
=> #661 updated tests and json to fit to the osis-common/document/paper_sheet.py file

performance/static/js/performance_result.js, performance/templates/performance_result.html
Inform the ticket you are solving in this pull request: #685
=> #685 modifs etat et colonne Inscr

performance/models/student_performance.py, performance/queue/student_performance.py, performance/static/js/performance_result.js, performance/tests/models/test_student_performance.py, performance/tests/queue/test_queue_student_performance.py, performance/tests/ressources/update_expate_with_registration_id.json, performance/tests/ressources/update_expate_without_registration_id.json
Inform the ticket you are solving in this pull request: #680
=> #680 update exp_date pour 1 student

performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po, performance/models/student_performance.py, performance/queue/student_performance.py, performance/static/js/performance_result.js, performance/templates/performance_result.html, performance/tests/queue/test_queue_student_performance.py, performance/tests/ressources/update_expate_with_registration_id.json, performance/tests/ressources/update_expate_without_registration_id.json, performance/views/main.py
Inform the ticket you are solving in this pull request: #702
=> Feature#702

performance/queue/student_performance.py, performance/templates/performance_result.html
Inform the ticket you are solving in this pull request: #702
=> #702 verifier si update_date existe avant division en sec

performance/queue/student_performance.py
Inform the ticket you are solving in this pull request: #702
=> #702 oubli add avant commit

frontoffice/settings.py
Inform the ticket you are solving in this pull request: #720
=> Bugfix#702 (Merge to Qa)

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/students_list.html, attribution/tests/views/test_online_application.py, attribution/views/tutor_charge.py, base/models/learning_unit_enrollment.py, base/models/learning_unit_year.py
Inform the ticket you are solving in this pull request: #724
=> Feature/724 correction pour que la liste des étudiants affiche aussi les étudiants des classes/partims

dashboard/views/score_encoding.py, performance/queue/student_performance.py
Inform the ticket you are solving in this pull request: #728
=> Bugfix#728 (Merge to Dev)

dashboard/views/score_encoding.py, performance/queue/student_performance.py
Inform the ticket you are solving in this pull request: #728
=> Bugfix#728 (Merge to Qa)

base/views/common.py
Inform the ticket you are solving in this pull request: #737
=> #737 modification return url for login method (Merge to Qa)

base/views/common.py
Inform the ticket you are solving in this pull request: #747
=> Bugfix#747 (Merge to Dev)

dashboard/views/score_encoding.py, frontoffice/queue/queue_listener.py, frontoffice/settings.py, performance/queue/student_performance.py
Inform the ticket you are solving in this pull request: #754
=> Bugfix#754 (Merge to Dev)

dashboard/views/score_encoding.py, frontoffice/queue/queue_listener.py, frontoffice/settings.py, performance/queue/student_performance.py
Inform the ticket you are solving in this pull request: #754
=> #754 maj osis-common et gestion des erreurs de connexion DB (Merge to Qa)

dashboard/views/score_encoding.py, performance/queue/student_performance.py
Inform the ticket you are solving in this pull request: #750
=> #750 generic db exception (Merge to Dev)

dashboard/views/score_encoding.py, performance/queue/student_performance.py
Inform the ticket you are solving in this pull request: #750
=> #750 generic db exception (Merge to Qa)

performance/queue/student_performance.py
Inform the ticket you are solving in this pull request: #750
=> #750 modif logger queue + ref osis-common (Merge to Dev)

performance/queue/student_performance.py
Inform the ticket you are solving in this pull request: #750
=> #750 modif logger queue + ref osis-common (Merge to Qa)

performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po, performance/views/main.py
Inform the ticket you are solving in this pull request: #765
=> #765 n'afficher que les offres dont l'etat d'inscription est valide (Merge to Qa)

dashboard/templates/dashboard.html
Inform the ticket you are solving in this pull request: #701
=> #701 added condition 'exam_enrollment' in installed apps

performance/templates/performance_result.html
Inform the ticket you are solving in this pull request: #811
=> #811 supression phrase dans affichage

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/dashboard.html
Inform the ticket you are solving in this pull request: #741
=> feature/741 (added traductions)

performance/static/js/performance_result.js
Inform the ticket you are solving in this pull request: #824
=> #824 modifictaion ordre nom/prenom

dissertation/models/dissertation_update.py
Inform the ticket you are solving in this pull request: #832
=> feature/832 add search criteria for dissertation_update

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/score_encoding.html, dashboard/templates/tutor_dashboard.html
Inform the ticket you are solving in this pull request: #833
=> #833 Correct text 'Score encoding' to 'My Score Sheets' in dashboard

dashboard/templates/tutor_dashboard.html
Inform the ticket you are solving in this pull request: #833
=> #833 Align 'Mes candidatures' to left on dashboard

performance/static/js/performance_result.js
Simple fix. No need to wait for Gaetan to be back.
=> Fix typo in perf results list :bug:

base/static/js/osis-portal.js
Inform the ticket you are solving in this pull request: #32
=> Correction

exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/views/main.py
Inform the ticket you are solving in this pull request: #698
=> #698 updated message to be more clear

internship/tests/views/test_hospital.py, internship/tests/views/test_main.py, internship/tests/views/test_master.py, internship/tests/views/test_resume.py, internship/views/hospital.py, internship/views/main.py, internship/views/master.py, internship/views/resume.py
Inform the ticket you are solving in this pull request: #815
=> corrected permission

admission/views/curriculum.py
Inform the ticket you are solving in this pull request: #41
=> #41 Correction bug d'affichage de Curriculum pour les Admissions

dashboard/templates/student_dashboard.html
Inform the ticket you are solving in this pull request: #883
=> feature 883 (correction)

internship/locale/en/LC_MESSAGES/django.po, internship/locale/fr_BE/LC_MESSAGES/django.po, internship/tests/views/test_main.py, internship/views/main.py
Inform the ticket you are solving in this pull request: #912
=> corrected display message

internship/models/internship_choice.py, internship/models/internship_offer.py, internship/models/internship_student_affectation_stat.py, internship/models/organization.py, internship/models/organization_address.py, internship/models/period_internship_places.py
Inform the ticket you are solving in this pull request: #918
=> added search field for admin page

exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/tests/resources/exam_enrollment_form_example.json, exam_enrollment/tests/views/test_exam_enrollment_form.py, exam_enrollment/views/main.py
Inform the ticket you are solving in this pull request: #937
=> #937 treatment of error_messages returned from EPC in JSON examEnrollmentForm (to get more explicit error messages)

exam_enrollment/templates/exam_enrollment_form.html
Inform the ticket you are solving in this pull request: #933
=> #933 Change label student to last_name, first_name

attribution/tests/utils/test_permission.py
Inform the ticket you are solving in this pull request: #946
=> #946 Use Timedelta instead of logic operator +/-

exam_enrollment/tests/views/test_exam_enrollment_form.py, exam_enrollment/views/main.py
Inform the ticket you are solving in this pull request: #940
=> #940 submitted form must contain only examEnrollments where etat_to_inscr is not None (+ unit test)

exam_enrollment/views/main.py
Inform the ticket you are solving in this pull request: #948
=> #948 removed forgotten unused code

attestation/templates/attestation_home.html, attestation/views/main.py, dashboard/views/main.py, exam_enrollment/views/main.py, internship/views/main.py, internship/views/resume.py, performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po, performance/templates/performance_home.html, performance/views/main.py
Inform the ticket you are solving in this pull request: #923
=> #923 gestion des cas de noma multiple pour les application sdu dashboard

exam_enrollment/templates/exam_enrollment_form.html, exam_enrollment/templates/offer_choice.html
Inform the ticket you are solving in this pull request: #933
=> #933 changed lable 'student' to 'Last name, First name'

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #923
=> #923 correction orthographe + dplacement

exam_enrollment/models/exam_enrollment_submitted.py
Inform the ticket you are solving in this pull request: #964
=> Added ondeletecascade constraint to the table exam_enrollment_submitted.

performance/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #968
=> #968 correction textes

exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/templates/exam_enrollment_form.html
Inform the ticket you are solving in this pull request: #963
=> Added message on top of the button.

exam_enrollment/templates/exam_enrollment_form.html
Inform the ticket you are solving in this pull request: #963
=> Added message on top of the button in a alert box.

internship/views/main.py
=> Makes sure students can choose

internship/models/internship_offer.py, internship/templates/internship_selection.html, internship/tests/models/test_internship_offer.py, internship/views/main.py, internship/views/resume.py
=> Change internship behaviour

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #967
=> feature/967 Corrections orthographiques

internship/views/main.py
=> Fix student scope when multiple students have chosen internships

internship/views/main.py
=> Fix student scope

internship/models/internship_offer.py, internship/views/main.py
=> Allow offers without a master to show up

internship/models/internship_offer.py, internship/views/main.py
=> Allow empty masters

base/models/offer_year.py, dissertation/models/offer_proposition.py, dissertation/views/dissertation.py
restreindre les offer_year_start proposés à ceux liés à un offer_proposition via offer
Inform the ticket you are solving in this pull request: #1006
=> feature/1006 restreindre les offer_year_start 

dissertation/locale/en/LC_MESSAGES/django.po, dissertation/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #636
=> feature/636 correction texte dans fichiers .po

internship/views/main.py
=> Fix sorting

dissertation/locale/en/LC_MESSAGES/django.po, dissertation/locale/fr_BE/LC_MESSAGES/django.po, dissertation/templates/dissertation_detail.html
Inform the ticket you are solving in this pull request: #903
=> #903 remove unnecessary js code + add missing traductions

base/views/common.py, frontoffice/settings.py
Inform the ticket you are solving in this pull request: #993
=> #993 Correction/Suppression de code dupliqué

base/models/signals.py
Inform the ticket you are solving in this pull request: #1000
=> Feature#1000

base/urls.py
Inform the ticket you are solving in this pull request: #1000
=> #1000 url / renvoie vers dashborad

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #917
=> #917 correction traduction

exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #917
=> #917 traductions

assessments/tests/ressources/score_encoding_sample.json
Inform the ticket you are solving in this pull request: #1061
=> #1061 updated reference to osis_common

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #1074
=> #1074 Remove duplicate translation

.gitignore, performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po, performance/templates/admin/performance_result_admin.html, performance/templates/performance_home.html, performance/templates/performance_home_student.html, performance/templates/performance_result.html, performance/templates/performance_result_student.html
Inform the ticket you are solving in this pull request: #1045 
@htmfilho Amélioration après tests en Dev, avant tests de Hang
=> #1045 corrections après tests en dev

attribution/templates/students_list_content.html, attribution/views/tutor_charge.py
Inform the ticket you are solving in this pull request: #1085
=> Moved the envelop to the left

attribution/templates/students_list_content.html
Inform the ticket you are solving in this pull request: #1085
=> Changed the sequence of fields to show scores.

assessments/templates/score_encoding.html, dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po
Inform the ticket you are solving in this pull request: #1093
=> #1093 Change displayed text --> qa

internship/utils/sync_internship_choices.py
Initialy only on Osis but because we switched from using models to using raw sql, we need to have this running on portal as well when needed.
=> Add internship choices sync script to portal

performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po, performance/static/js/performance_result.js, performance/templates/performance_result.html
=> Feature#1114 (Merge to Dev)

base/templates/layout.html, performance/templates/performance_result.html
=> #1114 Correction pr #1116 (Merge to Dev)

base/views/layout.py
=> #1114 reload du js (Merge to Dev)

performance/static/js/performance_result.js
=> #1114 gestion des objet 'undefined'(Merge to Dev)

.env.example, assessments/templates/score_encoding.html, assessments/views/score_encoding.py, base/static/css/custom.css, dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, frontoffice/settings/base.py
Inform the ticket you are solving in this pull request: #1122
=> #1122 Warning + bold orange text --> QA

.env.example, assessments/templates/score_encoding.html, assessments/views/score_encoding.py, base/static/css/custom.css, dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, frontoffice/settings/base.py
Inform the ticket you are solving in this pull request: #1122
=> #1122 Warning + bold orange text --> DEV

performance/static/js/performance_result.js
=> #1114 mise au frigo de la fonctionnalité

performance/static/js/performance_result.js
=> #1114 afichage du tableau recapitulatif des crédits

frontoffice/wsgi.py
Inform the ticket you are solving in this pull request: #1081
=> #1081 Reindent block if 'assessments'

base/models/signals.py
Inform the ticket you are solving in this pull request: #1146
=> Feature#1146

base/models/learning_unit_enrollment.py
Inform the ticket you are solving in this pull request: #1144
=> #1144 Improve search of LearningUnitEnrollment in admin

base/models/signals.py, internship/models/internship_student_information.py, internship/tests/models/test_internship_student_information.py
…ut dan sle groupe internship_students
Inform the ticket you are solving in this pull request: #1160
=> #1160 gestion de plusieur intenship_student_information lors de l'ajo… (Merge to Qa)

base/models/signals.py, internship/models/internship_student_information.py, internship/tests/models/test_internship_student_information.py
Inform the ticket you are solving in this pull request: #1160
=> #1160 correction ajout groupe si plusieur intership_user_info (Merge to Master)

attribution/locale/en/LC_MESSAGES/django.po, attribution/templates/tutor_charge_content.html
Inform the ticket you are solving in this pull request: #1170
=> removed display of total allocation charge row + fixed english translation

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/tutor_charge_content.html
=> Release 0.19.2

attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py
Inform the ticket you are solving in this pull request: #1175
=> corrected json key for tutor practical charge

attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py
Inform the ticket you are solving in this pull request: #1188
=> accept a dictionnary in place of a list when a tutor has single attibution

attribution/views/tutor_charge.py
=> #OSIS-8 set timeout for request when accessing attribution web service

attribution/views/tutor_charge.py
Inform the ticket you are solving in this pull request:
=> Bugfix/8 Traiter l'erreur quand le service web ne renvoi pas de réponse après 180 secondes

attribution/views/tutor_charge.py, base/models/academic_year.py
=> L'année académique actuelle et plus récent doit s'afficher par défaut

attribution/templates/tutor_charge_content.html, attribution/views/tutor_charge.py, base/models/academic_year.py
=> Qa vers Dev

attribution/templates/tutor_charge_content.html, attribution/views/tutor_charge.py, base/models/academic_year.py
=> Release 0.19.5

attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py
Inform the ticket you are solving in this pull request: #OSIS-40
=> Corriger l'adresse email des listes de difusion sur la charge d'enseignement

.env.example, attribution/templates/tutor_charge_content.html, attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py, base/models/academic_year.py, base/models/signals.py, frontoffice/settings/base.py
=> Release 0.19.6

assessments/templates/scores_sheets.html, assessments/views/score_encoding.py, frontoffice/settings/base.py
Inform the ticket you are solving in this pull request: #OSIS-173
=> #OSIS-173 Ajout du timeout en settings et env

attribution/templates/attribution_applications.html, dashboard/templates/tutor_dashboard.html
Inform the ticket you are solving in this pull request: #OSIS-202
=> #OSIS-202 Visualisation candidature en ligne

attestation/queues/student_attestation.py, attestation/views/main.py
https://uclouvain-sips.atlassian.net/browse/OSIS-197
=> OSIS-197 log exception when fetching student attestation to QA

exam_enrollment/templates/exam_enrollment_form.html, exam_enrollment/views/exam_enrollment.py
Inform the ticket you are solving in this pull request: #OSIS-207
=> #OSIS-207 To QA

exam_enrollment/templates/exam_enrollment_form.html, exam_enrollment/views/exam_enrollment.py
Inform the ticket you are solving in this pull request: #OSIS-207
=> Osis 207 To DEV

exam_enrollment/models/exam_enrollment_request.py, exam_enrollment/views/exam_enrollment.py
=> #OSIS-214 TO QA

exam_enrollment/models/exam_enrollment_request.py, exam_enrollment/views/exam_enrollment.py
Inform the ticket you are solving in this pull request: #Osis-214
=> #OSIS-214 TO DEV

exam_enrollment/models/exam_enrollment_request.py, exam_enrollment/views/exam_enrollment.py
Reverts uclouvain/osis-portal#1237
=> Revert "#OSIS-214 To QA"

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/admin/applications_administration.html, attribution/templates/application_form.html, attribution/templates/attribution_application_form.html, attribution/templates/attribution_applications.html, attribution/templates/attribution_vacant.html, attribution/templates/learning_unit_year_search.html, attribution/tests/views/test_online_application.py, attribution/urls.py, attribution/views/decorators/authorization.py, attribution/views/online_application.py, attribution/views/tutor_charge.py, base/tests/models/test_offer.py, dashboard/templates/faculty_administrator_dashboard.html, dashboard/views/main.py
Inform the ticket you are solving in this pull request: #OSIS-224
=> #OSIS-224 Ajout d'un accès comme facultaire pour les candidatures en ligne

attribution/views/list.py
Inform the ticket you are solving in this pull request: #OSIS-196
=> #OSIS-196 ADD log exception

dissertation/models/dissertation.py
Inform the ticket you are solving in this pull request: #OSIS-265
=> dissertation: add filter on dissertation inactive

base/models/campus.py
Inform the ticket you are solving in this pull request: #OSIS-233
=> #OSIS-233 Ajout pour l'admin

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/list/students_exam.html
Inform the ticket you are solving in this pull request: #OSIS-274
=> #OSIS-274 To QA

performance/urls.py, performance/views/main.py
Inform the ticket you are solving in this pull request: OSIS-290
=> Osis 290 (Merge to Dev)

performance/tests/views/test_main.py, performance/urls.py, performance/views/main.py
Inform the ticket you are solving in this pull request: OSIS-290
=> OSIS-290 Gestion des url "_" et tests

performance/models/student_performance.py, performance/views/main.py
Inform the ticket you are solving in this pull request: OSIS-290
=> OSIS-290 Prendre en compte la date de validite de la feuille de note

performance/queue/student_performance.py
Inform the ticket you are solving in this pull request: OSIS-290
=> Correction de l'affichage de la validation d'inscription aux cours

base/models/learning_container_year.py
=> set learning_container to raw_id_field

attestation/queues/student_attestation.py, attestation/tests/queues/test_student_attestation.py, attestation/tests/views/test_main.py, attestation/views/main.py
Inform the ticket you are solving in this pull request: OSIS-272
=> OSIS-272 envoyer le user lors du fetch du pdf des attestations

attribution/business/attribution.py, attribution/business/tutor_application.py, attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/application_form.html, attribution/templates/applications_list.html, attribution/templates/attribution_list.html, attribution/templates/attribution_overview.html, attribution/tests/business/test_attribution.py, attribution/tests/business/test_tutor_application.py, base/static/css/osis-portal.css
=> #OSIS-313 Correct Hang remarks

attribution/business/attribution.py, attribution/business/tutor_application.py, attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/application_form.html, attribution/tests/business/test_attribution.py, attribution/tests/utils/test_tutor_application_epc.py, attribution/utils/tutor_application_epc.py
=> #OSIS-313 Writing test and display error message

base/models/tutor.py
=> #OSIS-322 Add external_id to tutor model

attribution/tests/utils/test_tutor_application_epc.py, attribution/utils/tutor_application_epc.py
=> #OSIS-313 Correct Tutor application

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/admin/students_exam_list.html, attribution/templates/admin/students_list.html, attribution/tests/views/test_list.py, attribution/urls.py, attribution/views/list.py, attribution/views/tutor_charge.py, dashboard/templates/faculty_administrator_dashboard.html
Inform the ticket you are solving in this pull request: OSIS-310
=> OSIS-310 Adapt variables/views/params names to be more precise

attribution/business/tutor_application.py, attribution/templates/applications_list.html, attribution/templates/attribution_list.html, attribution/templates/attribution_renewal_list.html, attribution/templates/attribution_vacant_list.html
=> #OSIS-313 Display none value as zero decimal

base/models/offer_enrollment.py, base/tests/factories/offer_enrollment.py, exam_enrollment/tests/views/test_exam_enrollment.py, exam_enrollment/tests/views/test_exam_enrollment_form.py
Inform the ticket you are solving in this pull request: OSIS-360
=> [ PATCH to QA ] OSIS-360 filtering student's programs by enrollment state

frontoffice/settings/base.py
- Modification de la configuration des DB pour utiliser les transactions liées aux requets : ATOMIC_REQUEST = true
Inform the ticket you are solving in this pull request: # OSIS-369
=> OSIS-369 Database atomic request

base/models/offer_enrollment.py, base/tests/factories/offer_enrollment.py, exam_enrollment/tests/views/test_exam_enrollment.py, exam_enrollment/tests/views/test_exam_enrollment_form.py
Inform the ticket you are solving in this pull request: OSIS-360
=> [ merge to DEV ] OSIS-360 filtering student's programs by enrollment state

exam_enrollment/templates/exam_enrollment_form.html, exam_enrollment/templatetags/__init__.py, exam_enrollment/templatetags/slash_to__.py
- Transformation du "/" en "_" pour l'appel de l'url performance_student_by_acronym_and_year
Inform the ticket you are solving in this pull request: OSIS-362
=> OSIS-362  Gestion des acronyms avec "/" (Merge to Qa)

base/models/learning_unit_enrollment.py
=> OSIS-396 Add enrollment_state field to admin

base/models/learning_unit_enrollment.py
=> OSIS-396 Correct learning unit enrollment

attribution/templates/students_list_content.html
=> OSIS-412 fix url param

.travis.yml
=> updated travis.yml (postgresql version)

.travis.yml, travis-requirements.txt
=> Test travis (Merge to Dev)

.travis.yml, travis-requirements.txt
Pour debloquer travis , update version psycopg2
modif structure commune osis
=> Ajout requirements specifique travis (Merge to Qa)

requirements.txt, travis-requirements.txt
=> Correction requirements : openpyxl (Merge to Qa)

requirements.txt, travis-requirements.txt
=> PATCH Osis 467(dev)

.codeclimate.yml, .coveragerc, .travis.yml, requirements.txt, setup.cfg, travis-requirements.txt
=> Codeclimate

attribution/business/attribution.py, attribution/tests/business/test_attribution.py, base/tests/factories/learning_unit_year.py
=> OSIS-475 check index exist before use it in list + writing test

attribution/templates/attribution_vacant_list.html
=> [PATCH QA] OSIS-513 Correct Breadcrum Vacant List

frontoffice/settings/base.py
=> OSIS-466 Fix setting FORBIDDEN_SQL_KEYWORDS

attribution/templates/applications_list.html, attribution/templates/attribution_vacant_list.html, attribution/templatetags/urls_catalog.py, attribution/tests/templatetags/test_urls_catalog.py
=> [MERGE TO QA] OSIS-582 Correct templatetags + write tests on tags

attribution/templates/applications_list.html, attribution/templates/attribution_vacant_list.html, attribution/templatetags/urls_catalog.py, attribution/tests/templatetags/test_urls_catalog.py
=> [MERGE TO DEV] Osis 582

attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py, base/models/learning_unit_enrollment.py
Reverts uclouvain/osis-portal#1395
=> Revert "Osis 711"

exam_enrollment/templates/exam_enrollment_form.html
=> [MERGE TO QA] OSIS-754 Correct specific_title to title because data come from EPC

.env.example
=> OSIS-787 Modified env for url to manage courses

.env.docker
=> OSIS-803 Update database settings

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/tutor_dashboard.html
modifié :         dashboard/locale/en/LC_MESSAGES/django.po
modifié :         dashboard/locale/fr_BE/LC_MESSAGES/django.po
Référence Jira : OSIS-839
=> OSIS-839 Modification de la traduction de manage_courses

attribution/migrations/0020_auto_20180328_1315.py, base/migrations/0036_auto_20180328_1315.py
=> OSIS-899 Replace Select custom to cascade queries

attribution/migrations/0020_auto_20180328_1315.py, base/migrations/0036_auto_20180328_1315.py
=> OSIS-899 Correct Migration synchronisation

attribution/tests/views/test_tutor_charge.py, base/models/learning_unit_component.py, base/tests/factories/learning_unit_component.py, base/tests/models/test_learning_unit_component.py
=> #OSIS-1297 Delete duration field in learning_unit_component.

exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/templates/exam_enrollment_form.html
=> [ PATCH QA ] OSIS-1354 updated translation and removed tooltip

.codeclimate.yml
=> Updated duplication and method complexity configuration (codeclimate)

exam_enrollment/templates/blocks/modal/exam_enrollment_confirm.html
=> OSIS-1621 Default url if no program

dashboard/templates/student_dashboard.html, exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/templates/blocks/modal/exam_enrollment_confirm.html, exam_enrollment/tests/views/test_exam_enrollment_form.py, exam_enrollment/views/exam_enrollment.py
=> Osis 1759 Exam confirmation modal

performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po
=> Osis 2049 (Merge to Dev)

performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po
=> Modification de l aphrase d etraitement de l'inscription au cours (Merge to Qa)

performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po, requirements.txt
=> Release 0.47.1

attribution/templates/students_list_content.html, requirements.txt
=> Osis 2065 (Merge to Dev)

attribution/templates/students_list_content.html, requirements.txt
=> Osis 2065 (Merge to Qa)

base/templates/layout.html
=> OSIS-2079 Add version querystring to custom.css

base/views/layout.py
=> OSIS-2081 updated cache refresh (statics) only when re-deploying project

attribution/templates/students_list_content.html
=> [MERGE TO QA] OSIS-2094 Correct no student learning unit message when data is present

attribution/templates/students_list_content.html
=> [MERGE TO DEV] Osis 2094

attribution/templates/students_list_content.html, base/views/layout.py
=> RELEASE 0.47.4

exam_enrollment/templates/blocks/modal/exam_enrollment_confirm.html
=> [ TO MASTER ] OSIS-2229 Fix link to exam submission

base/management/commands/makemessages.py
=> Custom makemessages

.env.example, frontoffice/settings/base.py
=> IUFC - update ref to continuing education

assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po, assessments/templates/admin/scores_sheets.html, assessments/templates/score_encoding.html, assessments/templates/scores_sheets.html, assessments/tests/views/test_score_encoding.py, assessments/views/score_encoding.py
=> fix-translation-assessments: refector translations; all tests pass.

performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po, performance/templates/admin/performance_administration.html, performance/templates/admin/performance_home_admin.html, performance/templates/admin/performance_result_admin.html, performance/templates/performance_home.html, performance/templates/performance_home_student.html, performance/templates/performance_result.html, performance/templates/performance_result_student.html, performance/tests/views/test_main.py, performance/views/main.py
=> Fix translation performance

.gitmodules
=> Remove mobility module because not not used anymore

assessments/tests/resources/score_encoding_sample.json
=> [Release] Test

base/models/academic_year.py, base/tests/factories/academic_year.py, base/tests/models/test_academic_year.py
=> Iufc 155 Add next and past functions on AcademicYear model

base/tests/factories/education_group.py, base/tests/factories/education_group_type.py, base/tests/factories/education_group_year.py
=> add education_group factories

attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py, base/models/learning_unit_year.py
=> Osis 356 - Corriger la liste des étudiants inscrits aux cours

attribution/templates/attribution_overview.html
=> #OSIS-517 Amélioration visuelle pour l'icone d'envoi déplacement du bouton + coloration

base/models/education_group.py, base/tests/models/test_education_group.py
Référence Jira : OD-40 modification de most_recent_acronym pour Education_group
=> OD-40 modification de most_recent_acronym pour Education_group

base/models/education_group.py, base/tests/models/test_education_group.py
=> [Merge] Test

base/models/education_group.py, base/models/education_group_year.py, base/tests/models/test_education_group.py, base/tests/models/test_education_group_year.py
=> OD-40 add 2 functions and tests

base/models/education_group.py, base/tests/models/test_education_group.py
=> OD-40 adaptation function fing_by_student

attribution/templates/applications_list.html, attribution/tests/business/test_attribution.py, attribution/tests/views/test_list.py, attribution/tests/views/test_online_application.py, base/tests/factories/academic_year.py
=> #PATCH-2508 Erreur lors de la soumission d'une candidature

base/models/entity.py, base/tests/factories/entity.py, base/tests/models/test_entities.py
=> Add most_recent_acronym to EntityVersion

base/templates/template_messages.html
=> Fix extra margin between alerts used for messages display

attribution/forms/application.py, base/models/entity_version.py, base/tests/models/test_entity_version.py
=> Osis 516 - Ordonner la liste + notion de validité

base/static/js/modal_form_submit.js, base/templates/layout.html, base/views/mixin.py
=> Import scripts to manage ajax modals from OSIS

base/templates/layout.html, frontoffice/settings/base.py, frontoffice/urls.py, requirements.txt
=> Ajout Hijack

base/tests/views/autocomplete/test_education_group_year.py, base/views/autocomplete/common.py, base/views/autocomplete/country.py, base/views/autocomplete/education_group_year.py
=> Country Autocomplete Suite

.env.example, frontoffice/settings/base.py
=> ref osis_common messaging refactoring + settings

base/tests/factories/academic_year.py, base/tests/views/autocomplete/test_country.py, base/tests/views/autocomplete/test_education_group_year.py, base/views/autocomplete/common.py
=> Filter in autocomplete

base/tests/views/autocomplete/test_country.py, base/views/autocomplete/country.py
=> Iso code instead of UUID

dashboard/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/templates/blocks/modal/exam_enrollment_confirm.html, exam_enrollment/templates/exam_enrollment_form.html, exam_enrollment/templates/offer_choice.html
=> OSIS-2741 fixed translations for exam enrollments and dashboard

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/tutor_dashboard.html
=> #OSIS-2708 Modifier 'information pédagogique' en 'fiche descriptive'

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/tutor_dashboard.html
=> #OSIS-2708 Modif trad

requirements.txt
=> Updated packages

base/templates/layout.html
=> OSIS-2762 html dans notice osis-portal

base/views/layout.py, frontoffice/urls.py, requirements.txt
=> Vulnerabilities

requirements.txt
=> TEST Revert Django version to 1.11.2

attribution/templates/attribution_renewal_list.html
=> #OSIS-2606 Affichage du titre de l'année suivante

base/urls.py
=> Fix url for country autocomplete

attribution/urls.py, frontoffice/urls.py
=> Suppress jsi18n urls

requirements.txt
=> Updated Django to 1.11.20

attribution/business/attribution.py
=> #OSIS-2510 ordonner la liste des cours vacants en fonction de l'acronym

attribution/business/attribution.py
=> #OSIS-2510 Ordonner la liste des cours vacants

performance/views/main.py
=> bug apres refactoring (Merge to Dev)

base/models/offer_year.py, base/models/person.py, base/templates/layout.html, base/tests/views/test_api.py, base/tests/views/test_common.py, base/views/api.py, base/views/common.py, base/views/layout.py, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/dashboard_admin_menu.html, dashboard/templates/faculty_administrator_dashboard.html, dashboard/views/main.py, frontoffice/settings/base.py, performance/tests/views/test_main.py, performance/views/main.py
=> Osis 3083(Merge to Qa)

attribution/tests/business/test_attribution.py, attribution/tests/models/test_attribution_new.py
=> Use assertEqual

base/views/common.py, performance/views/main.py
=> Osis 3160 for dev (Updated with Dev Branch)

base/tests/views/test_common.py, base/views/common.py, performance/tests/views/test_main.py, performance/views/main.py
=> Osis 3160 (Merge to Qa)

exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/tests/views/test_exam_enrollment_form.py, exam_enrollment/views/exam_enrollment.py
=> [To Dev] OSIS-3163 Translate error message outside_exam_enrollment_period + test

base/templates/layout.html
Pull request automatique de hotfix/OSIS-3307 vers QA
=> [hotfix/OSIS-3307 => QA] Permettre les tag html dans la notice (osis-portal)

attestation/locale/en/LC_MESSAGES/django.po, attestation/locale/fr_BE/LC_MESSAGES/django.po, attestation/models/enums/attestation_type.py
Pull request automatique de hotfix/OSIS-3474 vers QA
=> [hotfix/OSIS-3474 => QA] (190957) Bureau virtuel des étudiants : présentations des attestations aux étudiants à améliorer

attestation/locale/en/LC_MESSAGES/django.po, attestation/locale/fr_BE/LC_MESSAGES/django.po, dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/faculty_administrator_dashboard.html
Pull request automatique de hotfix/OSIS-3542 vers QA
=> [hotfix/OSIS-3542 => QA] Modification des traduction des attestations et menu d_administration des notes

attestation/locale/en/LC_MESSAGES/django.po, attestation/locale/fr_BE/LC_MESSAGES/django.po, dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/faculty_administrator_dashboard.html
Pull request automatique de hotfix/OSIS-3542 vers DEV
=> [hotfix/OSIS-3542 => DEV] Modification des traduction des attestations et menu d_administration des notes

attribution/business/attribution.py, attribution/tests/business/test_attribution.py, attribution/tests/views/test_online_application.py
=> Fix test failed in attribution

base/tests/models/test_academic_year.py
=> #OSIS-3618 Correction des tests

base/tests/models/test_academic_year.py
Pull request automatique de hotfix/OSIS-3618 vers QA
=> [hotfix/OSIS-3618 => QA] Tests AcademicYear échouent

dashboard/templates/dashboard_admin_menu.html, dashboard/templates/faculty_administrator_dashboard.html
=> [hotfix/OSIS-3616 => QA] Problème d_accès au BVE pour les gestionnaires de programmes (Correction)

base/tests/views/test_api.py, base/tests/views/test_common.py, base/views/common.py, dashboard/templates/dashboard_admin_menu.html, dashboard/templates/faculty_administrator_dashboard.html, dashboard/views/main.py, performance/tests/views/test_main.py, performance/views/main.py
Pull request automatique de hotfix/OSIS-3616 vers MASTER
=> [hotfix/OSIS-3616 => MASTER] Problème d_accès au BVE pour les gestionnaires de programmes

attribution/business/attribution.py, attribution/tests/business/test_attribution.py
Pull request automatique de hotfix/OSIS-3635 vers QA
=> [hotfix/OSIS-3635 => QA] Test qui plante dans attribution

attribution/business/attribution.py, attribution/tests/business/test_attribution.py
Pull request automatique de hotfix/OSIS-3635 vers DEV
=> [hotfix/OSIS-3635 => DEV] Test qui plante dans attribution

attribution/models/attribution.py, attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py
Pull request automatique de hotfix/OSIS-3633 vers QA
=> [hotfix/OSIS-3633 => QA] Listes xls des professeurs reprennent les étudiants des partims et cours complet confondus

attribution/models/attribution.py, attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py
Pull request automatique de hotfix/OSIS-3633 vers DEV
=> [hotfix/OSIS-3633 => DEV] Listes xls des professeurs reprennent les étudiants des partims et cours complet confondus

.gitignore, .idea/externalDependencies.xml, .idea/inspectionProfiles/Default.xml, .idea/inspectionProfiles/Osis.xml, .idea/inspectionProfiles/profiles_settings.xml, .idea/vcs.xml
=> add config idea

.travis.yml, manage.py
=> Travis logs

assessments/templates/score_encoding.html, dashboard/templates/faculty_administrator_dashboard.html, dashboard/templates/student_dashboard.html, dashboard/templates/tutor_dashboard.html
=> Revert <em> to <i> for icons

exam_enrollment/templates/exam_enrollment_form.html
=> [To QA] OSIS-3806 fixed template code format (exam_enrollment)

exam_enrollment/templates/exam_enrollment_form.html
=> [To Dev] OSIS-3806 fixed template code format

reference/tests/factories/country.py
=> add get_or_create meta in CountryFactory

base/static/css/osis-portal.css
=> Fix autocomplete rendering

attestation/tests/views/test_main.py
=> Test Attestation

dashboard/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de hotfix/OSIS-4178 vers QA
=> [WIP] [hotfix/OSIS-4178 => QA] Bug traduction _Mes applications_ en _Mes candidatures_

attribution/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de hotfix/OSIS-4180 vers QA
=> [WIP] [hotfix/OSIS-4180 => QA] Bug enfant des facultés non pris en compte dans le filtre de recherches pour les nouvelles candidatures

attribution/templatetags/urls_catalog.py, attribution/tests/templatetags/test_urls_catalog.py
Pull request automatique de hotfix/OSIS-4184 vers QA
=> [WIP] [hotfix/OSIS-4184 => QA] Corriger l_URL du code qui redirige vers le partim

attribution/business/attribution.py, attribution/tests/business/test_attribution.py
Pull request automatique de hotfix/OSIS-4185 vers QA
=> [WIP] [hotfix/OSIS-4185 => QA] cours gérés en équipe ne doivent pas être cliquables

attribution/business/attribution.py, attribution/business/tutor_application.py, attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/application_form.html, attribution/templates/applications_list.html, attribution/tests/business/test_tutor_application.py, attribution/tests/views/test_online_application.py
Pull request automatique de hotfix/OSIS-4181 vers DEV
=> [hotfix/OSIS-4181 => DEV] Bug: Cours _gérés en équipe_ non présent dans la liste _Tous_

attribution/templatetags/urls_catalog.py, attribution/tests/templatetags/test_urls_catalog.py
Pull request automatique de hotfix/OSIS-4184 vers DEV
=> [hotfix/OSIS-4184 => DEV] Corriger l_URL du code qui redirige vers le partim

attribution/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de hotfix/OSIS-4180 vers DEV
=> [hotfix/OSIS-4180 => DEV] Bug enfant des facultés non pris en compte dans le filtre de recherches pour les nouvelles candidatures

dashboard/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de hotfix/OSIS-4178 vers DEV
=> [hotfix/OSIS-4178 => DEV] Bug traduction _Mes applications_ en _Mes candidatures_

attribution/business/attribution.py, attribution/business/tutor_application.py, attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/application_form.html, attribution/templates/applications_list.html, attribution/templatetags/urls_catalog.py, attribution/tests/business/test_attribution.py, attribution/tests/business/test_tutor_application.py, attribution/tests/templatetags/test_urls_catalog.py, attribution/tests/views/test_online_application.py, dashboard/locale/fr_BE/LC_MESSAGES/django.po
=> Release 2.4.1

attribution/business/attribution.py, attribution/business/tutor_application.py, attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/application_form.html, attribution/templates/applications_list.html, attribution/tests/business/test_attribution.py, attribution/tests/business/test_tutor_application.py, attribution/tests/views/test_online_application.py
Pull request automatique de hotfix/OSIS-4185 vers MASTER
=> [hotfix/OSIS-4185 => MASTER] cours gérés en équipe ne doivent pas être cliquables

attribution/templatetags/urls_catalog.py, attribution/tests/templatetags/test_urls_catalog.py
Pull request automatique de hotfix/OSIS-4184 vers MASTER
=> [hotfix/OSIS-4184 => MASTER] Corriger l_URL du code qui redirige vers le partim

attribution/business/attribution.py, attribution/business/tutor_application.py, attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/application_form.html, attribution/templates/applications_list.html, attribution/tests/business/test_tutor_application.py, attribution/tests/views/test_online_application.py
Pull request automatique de hotfix/OSIS-4181 vers MASTER
=> [WIP] [hotfix/OSIS-4181 => MASTER] Bug: Cours _gérés en équipe_ non présent dans la liste _Tous_

attribution/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de hotfix/OSIS-4180 vers MASTER
=> [hotfix/OSIS-4180 => MASTER] Bug enfant des facultés non pris en compte dans le filtre de recherches pour les nouvelles candidatures

dashboard/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de hotfix/OSIS-4178 vers MASTER
=> [hotfix/OSIS-4178 => MASTER] Bug traduction _Mes applications_ en _Mes candidatures_

reference/tests/models/test_domain.py
=> setUpTestData Ref

dashboard/tests/test_main.py
=> setUpTestData Dashboard

attribution/business/attribution.py, attribution/tests/views/test_online_application.py
=> RC 2.4.4 Patch recherche cours vacants

attribution/business/attribution.py, attribution/tests/views/test_online_application.py
Pull request automatique de hotfix/OSIS-4215 vers MASTER
=> [hotfix/OSIS-4215 => MASTER] (206165) Résultat d_une recherche sur les cours vacants incorrect

assessments/tests/models/test_score_encoding.py, assessments/tests/views/test_download_paper_sheet.py, assessments/tests/views/test_score_encoding.py
=> Test assessments

performance/tests/models/test_student_performance.py, performance/tests/queue/test_queue_student_performance.py, performance/tests/views/test_main.py
=> setUpTestData Performance

requirements.txt
=> update django to 2.2.10

exam_enrollment/templates/exam_enrollment_form.html
Pull request automatique de hotfix/OSIS-4455 vers MASTER
=> [WIP] [hotfix/OSIS-4455 => MASTER] Bug affichage inscription examens

dashboard/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-4683 fix merge po file

requirements.txt
=> update pillow requirement

dashboard/locale/fr_BE/LC_MESSAGES/django.po
=> Fix translation

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/id_data.html, dashboard/tests/business/test_id_data.py, dashboard/tests/resources/esb_student_main_data.json, dashboard/tests/resources/student_id_data.json, dashboard/tests/resources/student_main_data.json
Pull request automatique de hotfix/OSIS-4719 vers MASTER
=> Release 2.11.5

exam_enrollment/templates/exam_enrollment_form.html, frontoffice/wsgi.py
=> OSIS-4716 : Location choice for exams

exam_enrollment/tests/views/test_exam_enrollment_form.py
=> OSIS-4716 : Add test

performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po, performance/templates/performance_result.html, performance/views/main.py
=> OSIS-4716 : Remove performance modif

performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po, performance/templates/performance_result.html, performance/views/main.py
=> [hotfix/OSIS-4716 => QA] Inscription examens : sur site ou pas

exam_enrollment/templates/exam_enrollment_form.html
=> OSIS-4716 : Add new_line & fix disabled property

exam_enrollment/templates/exam_enrollment_form.html
=> OSIS-4716 : use margin left

exam_enrollment/templates/exam_enrollment_form.html
=> OSIS-4716 : Fix conditions

exam_enrollment/templates/exam_enrollment_form.html
=>   [WIP] [hotfix/OSIS-4716 => QA] Inscription examens : sur site ou pas 

exam_enrollment/templates/exam_enrollment_form.html
=> OSIS-4716 : Fix disabled choices

exam_enrollment/templates/exam_enrollment_form.html
Référence Jira : OSIS-4716
Proposition de solution full JS au problème de tooltip html5 firefox.
@BenJneB si besoin :) 
=> OSIS-4716 JS validation of form

exam_enrollment/templates/exam_enrollment_form.html
=> OSIS-4716 : remove disabled

exam_enrollment/templates/exam_enrollment_form.html
=> [WIP] [hotfix/OSIS-4716 => QA] Inscription examens : sur site ou pas 

performance/templates/performance_result.html
=> [hotfix/OSIS-4741 => QA] Modification Etat inscription et notes (exammarks)

exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/templates/exam_enrollment_form.html
=> OSIS-4779 Change english text

exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/templates/exam_enrollment_form.html
Pull request automatique de hotfix/OSIS-4779 vers QA
=> [hotfix/OSIS-4779 => QA] Préciser textes formulaire covid inscription examens

exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/templates/exam_enrollment_form.html
Pull request automatique de hotfix/OSIS-4779 vers DEV
=> [hotfix/OSIS-4779 => DEV] Préciser textes formulaire covid inscription examens

exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-4779 Fix translation

.idea/inspectionProfiles/Osis.xml, exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/templates/exam_enrollment_form.html, exam_enrollment/views/exam_enrollment.py
=> OSIS-4783 Update js check of form + backend check

exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/templates/exam_enrollment_form.html, exam_enrollment/views/exam_enrollment.py
Pull request automatique de hotfix/OSIS-4783 vers QA
=> [hotfix/OSIS-4783 => QA] Changer logique validation formulaire examens

exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po
=> Translation

performance/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-4783 Translation

requirements.txt
=> [QA] IUFC-667 : pypdftk requirement

requirements.txt
=> [DEV] IUFC-667 : pypdftk requirement

requirements.txt
=> Release 2.14.1

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-4765 : Correction de traduction

attribution/business/student_specific_profile.py, attribution/business/xls_students_by_learning_unit.py, attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/students_list_content.html, attribution/templatetags/detail_student_specific_profile.py, base/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de hotfix/OSIS-4765 vers QA
=> [hotfix/OSIS-4765 => QA] En tant que prof, je veux identifier les étudiants PEPS dans la liste des étudiants des cours dont j_ai la charge

attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py
=> OSIS-5050 Display classes in tutor's charge list

attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py
=> OSIS-5050 Business fix : Do NOT show classes in tutor's charge list

attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py
Pull request automatique de hotfix/OSIS-5050 vers MASTER
=> [hotfix/OSIS-5050 => MASTER] (227966) Erreur inattendue sur ma charge d_enseignement

attribution/tests/business/test_attribution.py
=> [QA] fix tests with new academic year

exam_enrollment/tests/views/test_exam_enrollment_form.py, exam_enrollment/views/exam_enrollment.py
=> OSIS-5116 : Correct anac

attribution/business/tutor_application.py, attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-5235 : Candidature en ligne > typo mail de confirmation

attribution/views/list.py
=> OSIS-5286 get learning units according to starting academic year

attribution/views/list.py
=> Change current by starting

attribution/views/list.py
This reverts commit 2d5b4867e1132b6a7aab9633e0641de63a419ffa, reversing
changes made to 1895c960c6885b67851b070420b160a597dc90e5.
Référence Jira : OSIS-5286
=> [QA] Revert "Merge pull request #2150 from uclouvain/hotfix/OSIS-5286"

performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po, performance/templates/performance_result.html
=> OSIS-5294 : Not concerned

dashboard/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-5410 : Ajout d'un point en fin de ligne d'une traduction

dashboard/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de hotfix/OSIS-5410 vers QA
=> [hotfix/OSIS-5410 => QA] Portail étudiant > Mes données personnelles > Typo

attribution/business/student_specific_profile.py
=> OSIS-5473 : PEPS > Type PEPS > Remplacer "Non défini" par "-"

attribution/business/student_specific_profile.py
Pull request automatique de hotfix/OSIS-5473 vers MASTER
=> Release 3.0.12

attribution/business/attribution.py, attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-5448 : Modification tooltip si volume declared vacanc est nul

attribution/business/tutor_application.py, attribution/tests/business/test_tutor_application.py, attribution/tests/utils/test_tutor_application_osis.py, attribution/utils/tutor_application_osis.py
=> OSIS-4251 change field name access for json tutor application

attribution/utils/tutor_application_osis.py, base/models/learning_unit_year.py, base/tests/factories/learning_container.py
=> Hotfix/osis 4251 QA

attribution/tests/utils/test_tutor_application_osis.py, attribution/utils/tutor_application_osis.py
=> OSIS-4251 keep new applications on portal

attribution/business/tutor_application.py
=> OSIS-4251 lock update

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/applications_list.html, attribution/templates/blocks/modal/application_delete_confirm.html
=> OSIS-5452 : Ajout des traductions manquantes

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/blocks/modal/application_delete_confirm.html
=> OSIS-5452 : Correction d'une traduction

assessments/tests/resources/incorrect_format_sample.json, assessments/tests/resources/score_encoding_sample.json, assessments/tests/resources/undated_sample.json
Pull request automatique de hotfix/OSIS-5443 vers QA
=> [hotfix/OSIS-5443 => QA] Encodage des notes > PDF > remplacer _Cote_ par _Note_

attribution/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de hotfix/OSIS-5523 vers QA
=> [hotfix/OSIS-5523 => QA] Cohérence texte candidature

attribution/business/tutor_application.py, attribution/views/online_application.py
=> OSIS-5516 Use ApplicationCourseCalendar in search vacant courses

requirements.txt
Référence Jira : INTERNSHIP-217
=> INTERNSHIP-217 update ref internship

attribution/business/tutor_application.py
=> OSIS-5565 lock attribution when creating application

attribution/business/tutor_application.py
Pull request automatique de hotfix/OSIS-5565 vers MASTER
=> Release 3.1.3

requirements.txt
Référence Jira : INTERNSHIP-198
=> INTERNSHIP-198 update ref

attribution/calendar/application_courses_calendar.py, attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/attribution_access_denied.html, attribution/tests/business/test_application.py, attribution/tests/views/test_online_application.py, attribution/views/online_application.py, base/templatetags/academic_year_display.py, dashboard/templates/faculty_administrator_dashboard.html, dashboard/templates/tutor_dashboard.html, dashboard/views/main.py
=> OSIS-5616 Implement warning outside period for calendar

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po
Référence Jira : INTERNSHIP-206
=> [To Dev] OSIS-5646 missing dashboard translation

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po
=> [To QA] OSIS-5646 missing dashboard translation + update ref internship

exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/templates/exam_enrollment_form.html, exam_enrollment/views/exam_enrollment.py
Pull request automatique de hotfix/OSIS-5665 vers QA
=> [hotfix/OSIS-5665 => QA] Inscription aux exams > Formulaire d_inscription à conditionner en fonction de la période COVID

requirements.txt
Pull request automatique de hotfix/OSIS-5693 vers QA
=> [WIP] [hotfix/OSIS-5693 => QA] Ma charge d’enseignement ne fonctionne pas si la date de début est null

base/models/person.py
Pull request automatique de hotfix/OSIS-5696 vers QA
=> [hotfix/OSIS-5696 => QA] Affichage noms : enlever les middle_name

base/migrations/0070_studentspecificprofile_translation.py, exam_enrollment/views/exam_enrollment.py
=> OSIS-5694 : fix migration

attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py
=> OSIS-5714 display other collective attributions

attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py
Pull request automatique de hotfix/OSIS-5714 vers QA
=> [WIP] [hotfix/OSIS-5714 => QA] Les autres collectifs ne sont pas repris dans _mes charges d_enseignement_

requirements.txt
Référence Jira : INTERNSHIP-235
=> INTERNSHIP-235 update requirement sdk version

.travis.yml, requirements.txt
=> discard internship sdk requirement

assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po, assessments/templates/score_encoding.html, dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/tutor_dashboard.html
=> OSIS-5765 : Modification d'une traduction

assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po, assessments/templates/score_encoding.html, dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/tutor_dashboard.html
Pull request automatique de feature/OSIS-5765 vers DEV
=> [feature/OSIS-5765 => DEV] Changer lien + texte info VPN portal enseignant

attribution/models/remote_attribution_service.py, attribution/views/list.py, requirements.txt
=> OSIS-5834 update sdk and use with_classes filter in attribution service

attribution/models/remote_attribution_service.py, attribution/views/list.py, requirements.txt
Pull request automatique de hotfix/OSIS-5834 vers MASTER
=> Release 3.9.2

.env.example, dashboard/templates/tutor_dashboard.html, dashboard/views/main.py, frontoffice/settings/base.py
=> OSIS-5814 Add link to dissertation in osis

.env.example, dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/tutor_dashboard.html, dashboard/views/main.py, frontoffice/settings/base.py
Pull request automatique de feature/OSIS-5814 vers DEV
=> [feature/OSIS-5814 => DEV] En tant que prof, je veux pouvoir accéder à OSIS-Dissertation à partir du tableau de bord

.env.example, base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, base/templates/server_error.html, base/tests/views/test_common.py, base/views/common.py, frontoffice/settings/base.py
=> OSIS-5988 change error messages

frontoffice/settings/osis_sdk/utils.py
=> Add helper for get_user_token with custom headers

attribution/views/list.py
=> Fixedle non renvoi d'un acronym à la place d'une UE

attribution/views/list.py
Pull request automatique de hotfix/OSIS-6001 vers MASTER
=> Release 3.12.3

base/fixtures/groups.json
=> Remove permission for tutor permission

attribution/templates/admin/attribution_administration.html, performance/templates/admin/performance_administration.html
=> OSIS-6027 : Adaptation des breadcrumbs

performance/locale/en/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po, performance/templates/admin/performance_home_admin.html, performance/templates/admin/performance_result_admin.html
=> Application de la nouvelle traduction

requirements.txt
=> update requirements downgrade psycopg2-binary to 2.7.5

dashboard/templates/faculty_administrator_dashboard.html
=> OSIS-6063 : Masquer certains points de menu

dashboard/templates/faculty_administrator_dashboard.html
Pull request automatique de feature/OSIS-6063 vers DEV
=> [feature/OSIS-6063 => DEV] BV > Administration Facultaire > Supprimer les rubriques qui concernent les professeurs

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/services/attribution.py, attribution/templates/tutor_charge_content.html, attribution/tests/views/test_students_list.py, attribution/views/students_list.py, attribution/views/tutor_charge.py, requirements.txt
=> OSIS-6074 : Show classes in teaching charges

base/tests/models/test_signals.py
=> Fix test signaux

attribution/tests/views/test_tutor_charge.py, attribution/views/tutor_charge.py
=> OSIS-6073 : Do not take partim volume into total

base/static/css/custom.css
=> OSIS-3830 : blue lines for classes

attribution/business/xls_students_by_learning_unit.py
=> OSIS-5799 Ajout d'une ligne dans l'excel

attribution/templates/attribution_list.html, attribution/templates/attribution_renewal_list.html
=> (Candidature en ligne) Fix visual issue on tab

attestation/tests/queues/test_student_attestation_status.py, attestation/tests/views/test_main.py, attestation/urls.py, attestation/views/administration.py, attestation/views/download.py, attestation/views/home.py
=> OSIS-6128 : Attestations refactor

attribution/tests/views/test_list.py
=> OSIS-3830 fix test

attribution/services/enrollments.py, attribution/templates/students_list_content.html, attribution/tests/views/test_list.py, attribution/tests/views/test_students_list.py, attribution/views/students_list.py, base/static/css/osis-portal.css, base/templates/api/ordering.html, base/templates/api/pagination.html, base/templates/api/search.html, base/templatetags/api_template_tags.py, frontoffice/settings/osis_sdk/utils.py
=> Refacto into 5753

base/locale/en/LC_MESSAGES/django.po, base/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/models/exam_enrollment_request.py, exam_enrollment/services/learning_unit_enrollment.py, exam_enrollment/tests/views/test_enrollment_form.py, exam_enrollment/tests/views/test_offer_choice.py, exam_enrollment/views/enrollment_form.py
=> OSIS-5753 : Get ue enrollment by api

attribution/templates/students_list_content.html, attribution/tests/views/test_list.py, attribution/tests/views/test_students_list.py, attribution/views/students_list.py, base/static/css/osis-portal.css, base/templates/api/ordering.html, base/templatetags/api_template_tags.py, frontoffice/settings/osis_sdk/internship.py, frontoffice/settings/osis_sdk/utils.py, frontoffice/tests/settings/osis_sdk/test_internship.py, frontoffice/tests/settings/osis_sdk/test_learning_unit.py, frontoffice/tests/settings/osis_sdk/test_learning_unit_enrollment.py, frontoffice/tests/settings/osis_sdk/test_utils.py
=> OSIS-3830 provide extra in Paginated Response + enable ordering on column header

attribution/services/enrollments.py, attribution/tests/services/enrollments.py
=> Refactoring bureau virtuel fix

frontoffice/settings/osis_sdk/utils.py
=> OSIS-3830 optimize api calls

requirements.txt
=> OSIS-3830 update learning-unit-sdk requirement version

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/students_list_content.html
=> OSIS-3830 : Issue 13 : label

.gitignore, requirements.txt
=> Security update

attribution/templates/list/students_exam.html
=> OSIS-6206 : Fix tooltips

base/migrations/0087_auto_20211109_1711.py
=> OSIS-6214-fix-fichiers-migrations

base/static/css/osis-portal.css
=> OSIS-6215 : Amélioration de la visibilité de l'icone de tri

attestation/views/home.py
=> OSIS-6167 Use current_year as data_year

requirements.txt
=> OSIS-6167 : requirements

requirements.txt
=> OSIS-6219 retrieve patch 1.1.2 for sdk assessments

attestation/templates/attestation_content.html
=> OSIS-6167 Also disable red color on row when outside event

attribution/templates/list/students_exam.html
=> OSIS-6219 fix open strong tag in template

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/list/students_exam.html
=> OSIS-6219 edit messages for exam enrollments list

assessments/services/assessments.py, attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/list/students_exam.html, attribution/tests/views/test_list.py, attribution/views/list.py, base/static/css/osis-portal.css, requirements.txt
=>  [To QA] Release 4.0.1

attribution/locale/fr_BE/LC_MESSAGES/django.po
=> [QA] OSIS-6219 fix trans typo

attribution/locale/fr_BE/LC_MESSAGES/django.po
=> [DEV] OSIS-6219 fix trans typo

requirements.txt
=> OSIS-6264 : Requirements reference sdk

attribution/templates/students_list_admin.html, attribution/templates/tutor_charge_admin.html, attribution/tests/views/test_select_tutor_for_attribution.py, attribution/urls.py, attribution/views/select_tutor_for_attribution.py, attribution/views/tutor_charge.py, dashboard/templates/faculty_administrator_dashboard.html
=> OSIS-6274 : SelectTutorForAttribution

attestation/views/download.py, attestation/views/home.py, base/urls.py, dashboard/views/faculty_administration.py, dashboard/views/home.py, dashboard/views/student/id_data.py, exam_enrollment/views/enrollment_form.py, exam_enrollment/views/offer_choice.py, performance/tests/views/test_main.py, performance/tests/views/test_performance_home.py, performance/views/main.py, performance/views/performance_home.py
=> OSIS-6279 : DashboardHome & FacultyAdministration

attribution/tests/views/test_students_list.py, attribution/views/students_list.py, performance/tests/ressources/points.json
=> OSIS-6266 retrieve sessions_results for partims and classes

attribution/tests/factories/enrollment.py, attribution/tests/views/test_tutor_charge.py, base/services/offer_enrollment.py, base/utils/api_utils.py, exam_enrollment/services/learning_unit_enrollment.py, requirements.txt
=> Downgrade requirements

requirements.txt
=> [MASTER] update requirements for python 3.7

dashboard/views/student/my_personal_information.py
=> OSIS-6278 : Fix issue: no data displayed

attribution/templates/students_list_admin.html, attribution/templates/tutor_charge_admin.html, attribution/tests/views/test_select_tutor_for_attribution.py, attribution/urls.py, attribution/views/select_tutor_for_attribution.py, attribution/views/tutor_charge.py, dashboard/templates/faculty_administrator_dashboard.html
Pull request automatique de technical/OSIS-6274 vers DEV
=> [technical/OSIS-6274 => DEV] Class-based view : attributions :  Administration (SelectTutorForAttribution)

attribution/templates/applications_list.html, attribution/templates/tutor_attribution_list.html
Pull request automatique de technical/OSIS-6048 vers DEV
=> [technical/OSIS-6048 => DEV] Candidature en ligne > Mes candidatures + Mes charges > problème d_affichage

requirements.txt
=> OS-103 : sdk build 1.1 (organisation)

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/attribution_overview.html
=> OSIS-5615 : Button design

attribution/views/tutor_charge.py
Pull request automatique de hotfix/OSIS-6414 vers QA
=> [hotfix/OSIS-6414 => QA] (274444, 274492) Erreur inattendue lors de la consultation des charges d_enseignement

requirements.txt
=> Update organisation sdk requirements

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/attribution_overview.html
Pull request automatique de feature/OSIS-5615 vers DEV
=> [feature/OSIS-5615 => DEV] Candidature en ligne : modifier bouton Nouvelle Candidature

attribution/templates/attribution_list.html, requirements.txt
Pull request automatique de technical/OSIS-6051 vers DEV
=> [technical/OSIS-6051 => DEV] Candidature en ligne > ApiTypeError quand on essaie d_accéder au module

attribution/forms/application.py
=> OSIS-6423 : max_digits=6, decimal_places=2 for all volumes

attestation/templates/attestation_content.html
=> OSIS-6197 Fixed attribut error

attribution/forms/application.py
=> OSIS-6423 : Format correctly 2 decimals

manage_submodules.py
=> [QA] fix manage submodule when declaring more than 2 submodules

attribution/templates/tutor_charge_content.html
=> OSIS-6466 : fontawesome issue with fa-group

attribution/templates/tutor_charge_content.html
Pull request automatique de hotfix/OSIS-6466 vers MASTER
=> Release 4.1.2

requirements.txt
=> OSIS-6481 : sdk organization requirements

requirements.txt
See https://github.com/uclouvain/osis/pull/11453
=> Upgrade pylint

base/views/api.py, base/views/common.py
=> OSIS-6500 get user roles with person related api request headers

dashboard/views/student/my_personal_information.py
=> OSIS-6500 override permission for MyPersonalInformationAdmin to consider prgm managers

frontoffice/__init__.py, requirements.txt
=> Reference sdk req

base/tests/views/test_api.py, base/tests/views/test_common.py, base/views/api.py, base/views/common.py, performance/tests/views/test_main.py, performance/tests/views/test_performance_home.py, performance/views/main.py, performance/views/performance_home.py
=> OSIS-6508 discard annualization of managed programs when determining role access

base/tests/views/test_api.py, base/tests/views/test_common.py, base/views/api.py, base/views/common.py, performance/tests/views/test_main.py, performance/tests/views/test_performance_home.py, performance/views/main.py, performance/views/performance_home.py
Pull request automatique de hotfix/OSIS-6508 vers MASTER
=> Release 4.1.6

assessments/business/attendance_mark/permission.py, assessments/locale/en/LC_MESSAGES/django.po, assessments/locale/fr_BE/LC_MESSAGES/django.po, assessments/services/assessments.py, assessments/templates/assessments/attendance_mark/outside_period.html, assessments/templates/assessments/attendance_mark/select_offer.html, assessments/tests/factories/services/assessments.py, assessments/tests/views/attendance_mark/test_offers.py, assessments/views/attendance_mark/offers.py, assessments/views/attendance_mark/outside_period.py, attestation/locale/fr_BE/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, base/services/offer_enrollment.py, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, performance/locale/fr_BE/LC_MESSAGES/django.po
=> Osis 6231 display offers for attendance mark

exam_enrollment/admin.py, exam_enrollment/apps.py, exam_enrollment/enums/covid_exam_choice.py, exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/models/exam_enrollment_request.py, exam_enrollment/services/learning_unit_enrollment.py, exam_enrollment/templates/blocks/modal/exam_enrollment_confirm.html, exam_enrollment/templates/blocks/modal/no_enrollment_confirm.html, exam_enrollment/templates/exam_enrollment_form.html, exam_enrollment/templates/offer_choice.html, exam_enrollment/templatetags/slash_to__.py, exam_enrollment/tests/factories/exam_enrollment_request.py, exam_enrollment/tests/models/test_exam_enrollment_request.py, exam_enrollment/tests/views/test_check_form.py, exam_enrollment/tests/views/test_enrollment_form.py, exam_enrollment/tests/views/test_offer_choice.py, exam_enrollment/urls.py, exam_enrollment/views/check_form.py, exam_enrollment/views/enrollment_form.py, exam_enrollment/views/offer_choice.py, exam_enrollment/views/utils.py
=> OSIS-6306 : add modal to prevent student to save without enrollment

attribution/business/student_specific_profile.py, attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/students_list_content.html, attribution/tests/business/test_student_specific_profile.py, base/static/css/osis-portal.css, requirements.txt
=> OSIS-6580 adapt tooltip and legend for PEPS in teaching charge student list

attribution/business/student_specific_profile.py, attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/tests/business/test_student_specific_profile.py
=> OSIS-6580 format additional time and appropriate copy

attribution/business/xls_students_by_learning_unit.py
=> Osis 6581 fix comments

base/static/hijack/hijack-styles.css
=> OSIS-6698 : add css

frontoffice/settings/base.py
=> OSIS-6698 : add middleware

performance/views/main.py
=> OSIS-6509 : Améliortion formatage de l'heure

base/templates/layout.html, base/templates/osis_notification/notification_viewer.html
=> Make osis-notification optional

requirements.txt
=> OSIS-6749 : Adapt requirements for organization sdk

requirements.txt
=> downgrade-version-django-autocomplete-light

requirements.txt
=> OSIS-6767 : adapt osis-reference-sdk requirement

requirements.txt
=> downgrade-version-django-autocomplete-light-test

requirements.txt
=> downgrade-version-django-autocomplete-light-dev

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/attribution_renewal_list.html, base/static/js/attribution.js
=> OSIS-6498 Ajouter tooltip sur la reconduction des cours en échéance

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po, attribution/templates/attribution_renewal_list.html, base/static/js/attribution.js
Pull request automatique de feature/OSIS-6498 vers DEV
=> [feature/OSIS-6498 => DEV] [Campagne 2023]Ajouter un tooltip sur le bouton reconduction

requirements.txt
=> OSIS-6816 : update requirements

requirements.txt
=> Update requirements for reference sdk

assessments/urls.py, assessments/views/score_encoding.py
Pull request automatique de technical/OSIS-6919 vers DEV
=> [technical/OSIS-6919 => DEV] Supprimer vue et url inutilisée

.env.example, dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/dashboard.html, dashboard/views/home.py, frontoffice/settings/base.py
=> display temporary vpn warning message for tutors

requirements.txt
=> Update reference sdk requirements

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/dashboard.html, dashboard/views/home.py
=> OSIS-6757 fix tiles perms

.env.example, dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/dashboard.html, dashboard/views/home.py, frontoffice/settings/base.py
=> [QA] Remove notice

.env.example, dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/dashboard.html, dashboard/views/home.py, frontoffice/settings/base.py
=> [MASTER] remove temporary tutor notice

base/static/css/custom.css, dashboard/templates/dashboard.html, dashboard/templates/faculty_administrator_dashboard.html
=> OSIS-6987 remove "Dashboard" title from dashboard + fix administration_facultaire dashboard

assessments/views/attendance_mark/learning_units.py, assessments/views/attendance_mark/offers.py
=> OSIS-6862 manage student with double noma

assessments/views/attendance_mark/learning_units.py, assessments/views/attendance_mark/offers.py
Pull request automatique de hotfix/OSIS-6862 vers QA
=> [hotfix/OSIS-6862 => QA] Notes de présence > gérer les double nomas

requirements.txt
=> Update sdk requirements

frontoffice/settings/osis_sdk/mixins.py
=> OSIS-7032 : mixin to paginate api autocomplete

reference/services/iban_validator.py
=> IBAN Validator

requirements.txt
=> OSIS-7190 : update sdk requirements

attestation/queues/student_attestation.py, attestation/tests/queues/test_student_attestation.py, frontoffice/settings/base.py
Pull request automatique de hotfix/OSIS-7232 vers MASTER
=> [hotfix/OSIS-7232 => MASTER] Permettre de choisir 1 des seveurs EPC au hasard pour l_api des attestations

requirements.txt
=> OSIS-7299 : update sdk requirement

reference/services/iban_validator.py
=> RequestException for IBANValidator

reference/services/iban_validator.py
=> Use message from localflavore

reference/services/iban_validator.py
=> Update IBAN to QA

base/urls.py, base/views/iban_validator.py, reference/services/iban_validator.py
Pull request automatique de technical/OSIS-7386 vers DEV
=> [WIP] [technical/OSIS-7386 => DEV] Adapter IBANValidator pour fonctionner sans ESB sur DEV

frontoffice/settings/base.py
=> OSIS-7386 : fix settings

exam_enrollment/locale/en/LC_MESSAGES/django.po, exam_enrollment/locale/fr_BE/LC_MESSAGES/django.po, exam_enrollment/templates/exam_enrollment_form.html, exam_enrollment/views/enrollment_form.py
Pull request automatique de hotfix/OSIS-7424 vers MASTER
=> [hotfix/OSIS-7424 => MASTER] Retirer message destiné au 11BA pour les inscriptions aux examens (plus valable ajd)

attribution/business/xls_students_by_learning_unit.py
Pull request automatique de hotfix/OSIS-7482 vers QA
=> [hotfix/OSIS-7482 => QA] Impossible de générer les listes Excels des étudiants inscrits aux cours

attribution/business/xls_students_by_learning_unit.py
=> Fixed border

attribution/business/xls_students_by_learning_unit.py
=> [hotfix/OSIS-7482 => MASTER] Impossible de générer les listes Excels des étudiants inscrits aux cours

frontoffice/__init__.py, reference/services/iban_validator.py
=> Fix IBAN Validator

base/services/offer_enrollment.py, frontoffice/__init__.py, inscription_aux_cours/formatter.py, inscription_aux_cours/services/formulaire_inscription.py, inscription_aux_cours/static/inscription_aux_cours/css/inscription_aux_cours.css, inscription_aux_cours/static/inscription_aux_cours/js/inscription_aux_cours.js, inscription_aux_cours/templates/inscription_aux_cours/blocks/header_formation.html, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/desinscrire.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/inscriptibles.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/inscrire.html, inscription_aux_cours/templates/inscription_aux_cours/non_autorisee.html, inscription_aux_cours/templates/inscription_aux_cours/selectionner_formation.html, inscription_aux_cours/templatetags/inscription_aux_cours_extra.py, inscription_aux_cours/urls.py, inscription_aux_cours/views/common.py, inscription_aux_cours/views/cours/demande_particuliere.py, inscription_aux_cours/views/cours/formulaire.py, inscription_aux_cours/views/cours/recapitulatif.py, inscription_aux_cours/views/inscription_non_autorisee.py, inscription_aux_cours/views/mini_formation/inscriptibles.py, inscription_aux_cours/views/selectionner_formation.py, program_management/services/programme.py
=> Osis 7355 corrections inscription aux cours bv

inscription_aux_cours/locale/en/LC_MESSAGES/django.po, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/views/cours/recapitulatif.py, inscription_aux_cours/views/mini_formation/inscriptibles.py
=> OSIS-7355 translations

requirements.txt
=> OSIS-7528 : Update sdk requirements

inscription_aux_cours/static/inscription_aux_cours/js/inscription_aux_cours.js, inscription_aux_cours/templates/inscription_aux_cours/cours/desinscrire.html, inscription_aux_cours/templates/inscription_aux_cours/cours/inscrire.html
=> 7171 visual adaptations when enrolling and unenrolling from courses

base/templatetags/sort_extra.py, base/utils/string_utils.py, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/templates/inscription_aux_cours/cours/desinscrire.html, inscription_aux_cours/templates/inscription_aux_cours/cours/inscrire.html, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html, inscription_aux_cours/views/cours/formulaire.py, inscription_aux_cours/views/cours/recapitulatif.py
=> Osis 7175 corrections visuels inscriptions aux cours

inscription_aux_cours/static/inscription_aux_cours/css/formulaire.css, inscription_aux_cours/static/inscription_aux_cours/css/inscription_aux_cours.css, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/cours_hors_programme.html, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html
=> inscriptions aux cours améliorations visuels

inscription_aux_cours/static/inscription_aux_cours/css/print.css, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html
=> Osis 7179 imprimer proposition de pae

requirements.txt
=> OSIS-7567 : update version of reference sdk

requirements.txt
Pull request automatique de technical/OSIS-7567 vers DEV
=> [technical/OSIS-7567 => DEV] Schéma API - Intitulé de diplome : duration_type peut être null

inscription_aux_cours/forms/cours/demande_particuliere.py, inscription_aux_cours/static/inscription_aux_cours/css/print_proposition_programme_annuel.css
=> 7179 increase demande text size + fix print when in dev and qa mode

inscription_aux_cours/views/cours/formulaire.py
=> do not load api when no inscriptions hors programme

inscription_aux_cours/data/proposition_programme_annuel.py, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/proposition_programme_annuel_etudiant.html, inscription_aux_cours/views/cours/recapitulatif.py, requirements.txt
=> 7176 montre inscriptions pour partenariats dans recapitulatif

attribution/forms/application.py, base/models/entity_version.py
Pull request automatique de hotfix/OSIS-7593 vers MASTER
=> Release 4.13.2

attribution/business/student_specific_profile.py, attribution/templatetags/detail_student_specific_profile.py
=> OSIS-7635 : fix enum from sdk to display peps infos

attribution/views/students_list.py
=> OSIS-7635 : fix xls

attribution/business/student_specific_profile.py, attribution/templatetags/detail_student_specific_profile.py, attribution/views/students_list.py
Pull request automatique de hotfix/OSIS-7635 vers MASTER
=> [hotfix/OSIS-7635 => MASTER] BV prof > Ma charge d_enseignement > les détails des PEPS ne sont plus visibles

inscription_aux_cours/locale/en/LC_MESSAGES/django.po, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/static/inscription_aux_cours/css/spinner.css, inscription_aux_cours/static/inscription_aux_cours/js/spinner.js, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/layout.html, inscription_aux_cours/views/cours/inscrire_hors_programme.py
=> 7155 spinner quand ajout cours hors programme

inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/soumettre_proposition.html
=> fixe merge technical/OSIS-7355

inscription_aux_cours/templates/inscription_aux_cours/mini_formation/recapitulatif.html, inscription_aux_cours/views/cours/recapitulatif.py, inscription_aux_cours/views/mini_formation/recapitulatif.py
=> 7475 fixe cas version mini formation

inscription_aux_cours/views/cours/recapitulatif.py
=> 7158 fixe recap quand ue de mobilite hors contexte de parternariat

inscription_aux_cours/views/cours/desinscrire.py
=> 7639 garde etat inscription si desinscription echoue

requirements.txt
=> update django to 3.2.17

inscription_aux_cours/templates/inscription_aux_cours/mini_formation/inscriptibles.html
=> 7638 move warning minors options enrolled not proposed anymore

dashboard/business/id_data.py
=> OSIS-7656 : cast int to str

base/static/js/htmx-1.8.6.js, inscription_aux_cours/static/inscription_aux_cours/js/inscription_aux_cours.js, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/layout.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/inscriptibles.html
=> 7717 sync un.enroll of courses and mini_trainings

inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/soumettre_proposition.html, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html, inscription_aux_cours/views/cours/recapitulatif.py
=> 7641 bloque soumission si prerequis non acquis

inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/soumettre_proposition.html
=> 7641 tooltip on disabled pae submission button

base/static/js/htmx-1.8.6.js, inscription_aux_cours/static/inscription_aux_cours/js/inscription_aux_cours.js, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/layout.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/inscriptibles.html
Pull request automatique de technical/OSIS-7717 vers DEV
=> [technical/OSIS-7717 => DEV] [Bug inscription ETD] Certaines inscriptions se perdent

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/dashboard.html, dashboard/views/home.py
=> 7858 display header for student tiles

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/templates/dashboard.html, dashboard/views/home.py
Pull request automatique de technical/OSIS-7858 vers DEV
=> [technical/OSIS-7858 => DEV] Page d_accueil du BV étudiant > ajouter une nouvelle en-tête

frontoffice/settings/dev.example
=> add session cookie name in dev.example

inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html
=> 7895 adapt sync of courses enrollment requests

inscription_aux_cours/templates/inscription_aux_cours/blocks/barres_de_progression.html, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html, inscription_aux_cours/views/cours/desinscrire.py, inscription_aux_cours/views/cours/desinscrire_hors_programme.py, inscription_aux_cours/views/cours/formulaire.py, inscription_aux_cours/views/cours/inscrire.py, inscription_aux_cours/views/cours/inscrire_hors_programme.py
=> OSIS-7290 : progress in form

inscription_aux_cours/locale/en/LC_MESSAGES/django.po, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/static/inscription_aux_cours/css/inscription_aux_cours.css, inscription_aux_cours/static/inscription_aux_cours/css/print_proposition_programme_annuel.css, inscription_aux_cours/templates/inscription_aux_cours/blocks/barre_de_progression.html, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html, inscription_aux_cours/templatetags/inscription_aux_cours_extra.py, inscription_aux_cours/urls.py, inscription_aux_cours/views/common.py, inscription_aux_cours/views/cours/desinscrire.py, inscription_aux_cours/views/cours/inscrire.py, inscription_aux_cours/views/progression/barre_de_progression_de_bloc_1.py, inscription_aux_cours/views/progression/barre_de_progression_de_complement.py, inscription_aux_cours/views/progression/barre_de_progression_de_cycle.py
=> OSIS-7290 : Issues

frontoffice/settings/base.py, frontoffice/urls.py, requirements.txt
=> OSIS-7935 : try rosetta

dashboard/tests/views/test_home.py
=> Fix test_home.py

requirements.txt
=> Remove dissertation sdk from requirements

inscription_aux_cours/templates/inscription_aux_cours/blocks/barres_de_progression.html, inscription_aux_cours/views/cours/formulaire.py, inscription_aux_cours/views/cours/recapitulatif.py
=> OSIS-7917 : progress barr proportion

inscription_aux_cours/templates/inscription_aux_cours/blocks/barres_de_progression.html, inscription_aux_cours/views/cours/formulaire.py, inscription_aux_cours/views/cours/recapitulatif.py
Pull request automatique de technical/OSIS-7917 vers DEV
=> [technical/OSIS-7917 => DEV] garder la même proportion entre les deux barres de progression

inscription_aux_cours/views/cours/recapitulatif.py
=> OSIS-7173 : fix get detail training

requirements.txt
=> [To rc-master-5.0] fix requirements of transversal modules

requirements.txt
=> [To QA] fix requirements of transversal modules

education_group/services/training.py, inscription_aux_cours/views/cours/formulaire.py, inscription_aux_cours/views/cours/recapitulatif.py, requirements.txt
=> OSIS-7963 : update requirements + get correct credits

base/static/css/custom.css
=> OSIS-7937 ajout css pour les badges

base/static/js/osis-portal.js, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/desinscrire.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/inscrire.html
=> OSIS-7811 Mieux mettre en évidence la minini-formation sélectionnée + les clés cliquables

attestation/templates/attestation_content.html
=> Erreur dans html

base/static/css/custom.css, requirements.txt
Pull request automatique de technical/OSIS-7937 vers DEV
=> [technical/OSIS-7937 => DEV] Ajouter les badge E côté étudiant pour les UE échouées

inscription_aux_cours/templates/inscription_aux_cours/blocks/barre_de_progression.html
=> harmonize with progress bar from osis

frontoffice/settings/base.py, frontoffice/urls.py, requirements.txt
=> Install rosetta on TEST

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/views/home.py
Pull request automatique de technical/OSIS-8013 vers DEV
=> [technical/OSIS-8013 => DEV] Renommer la rubrique Programme annuel

requirements.txt
=> Update django to 3.2.19

inscription_aux_cours/static/inscription_aux_cours/css/inscription_aux_cours.css, inscription_aux_cours/templates/inscription_aux_cours/blocks/barres_de_progression.html, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html
=> OSIS-8112 remove progress bar from formulaire

inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html, inscription_aux_cours/views/cours/formulaire.py
=> OSIS-8113 preserve form input values after page is reloaded with errors

inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html
=> OSIS-8113 rename

inscription_aux_cours/locale/en/LC_MESSAGES/django.po, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/views/cours/proposition_programme_annuel.py
=> OSIS-8126 ajout message erreur

inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/cours_hors_programme.html, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html, inscription_aux_cours/views/cours/formulaire.py
Pull request automatique de technical/OSIS-8113 vers DEV
=> [technical/OSIS-8113 => DEV] Garder les choix de l_étudiant dans le formulaire en cas d_erreur à l_enregistrement

inscription_aux_cours/locale/en/LC_MESSAGES/django.po, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/proposition_programme_annuel_etudiant.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/desinscrire.html
Pull request automatique de technical/OSIS-8126 vers DEV
=> [technical/OSIS-8126 => DEV] Nouveau formulaire étudiant > Ajouter un message en cas d_erreur + ne pas bloquer l_inscription aux classes

dashboard/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po
Pull request automatique de technical/OSIS-8124 vers DEV
=> [technical/OSIS-8124 => DEV] Renommage Proposition/Composition à refaire pour la partie portail

inscription_aux_cours/services/pdf_pae_valide_jury.py, inscription_aux_cours/urls.py, inscription_aux_cours/views/cours/mon_pae_valide_jury.py, requirements.txt
=> OSIS-7220: redirection vers le pdf du pae validé jury

inscription_aux_cours/locale/en/LC_MESSAGES/django.po, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html
=> OSIS-8129 : move upper earned credits

requirements.txt
=> OSIS-8183 : update requirements

requirements.txt
Pull request automatique de technical/OSIS-8183 vers DEV
=> [technical/OSIS-8183 => DEV] Impossible d_accéder au formulaire de l_étudiant pour une formation isolée (sans crédits cibles)

inscription_aux_cours/views/common.py, program_management/services/programme.py
=> OSIS-7958 exclude phd and formation_phd from enrolment

inscription_aux_cours/locale/en/LC_MESSAGES/django.po, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/static/inscription_aux_cours/css/inscription_aux_cours.css, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/soumettre_proposition.html, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/formulaire.html
=> OSIS-7618 ez win responsive transmogrifications

requirements.txt
=> Upgrade osis-document version to 0.6

inscription_aux_cours/templates/inscription_aux_cours/blocks/barre_de_progression_de_complement.html, inscription_aux_cours/views/progression/barre_de_progression_de_complement.py
=> OSIS-8093 : barres de complement conditionnée

inscription_aux_cours/views/progression/barre_de_progression_de_complement.py
=> Fix complement progress bar condition

frontoffice/settings/osis_sdk/parcours_interne.py, inscription_aux_cours/services/proprietes_pae.py, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/soumettre_proposition.html, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html, inscription_aux_cours/views/cours/recapitulatif.py, requirements.txt
=> OSIS-8091 : check if has a condition in 1ADP or BAMA15

base/tests/factories/person.py
=> Fix other issue with mail

frontoffice/urls.py, inscription_aux_cours/views/cours/recapitulatif.py, requirements.txt
…les intitules des classes -> suppression de detail_classes
=> OSIS-8103: Performances : API : récupérer les intitulés des classes en 1 seul appel

requirements.txt
=> Update django 3.2.20

frontoffice/urls.py, inscription_aux_cours/views/cours/recapitulatif.py, requirements.txt
Pull request automatique de technical/OSIS-8103 vers DEV
=> [technical/OSIS-8103 => DEV] Performances : API : récupérer les intitulés des classes en 1 seul appel

inscription_aux_cours/templates/inscription_aux_cours/blocks/barre_de_progression.html, inscription_aux_cours/views/progression/barre_de_progression_de_bloc_1.py, inscription_aux_cours/views/progression/barre_de_progression_de_complement.py, inscription_aux_cours/views/progression/barre_de_progression_de_cycle.py
=> OSIS-8233 : fix for progress bars

requirements.txt
=> Move pendulum to internship and pypdftk to iufc

attribution/locale/en/LC_MESSAGES/django.po, attribution/locale/fr_BE/LC_MESSAGES/django.po
=> fixed_traduction_key

requirements.txt
=> Fix osis document 0.9

requirements.txt
=> version-osis-document: changement de la version d'osis-document en 0.91

inscription_aux_cours/views/cours/formulaire.py
Pull request automatique de technical/OSIS-8166 vers DEV
=> [technical/OSIS-8166 => DEV] Nouveau formulaire > désinscription d_un cours inscrit hors formulaire par le gestionnaire > comportement pas explicite

requirements.txt
=> [QA] Increment OSIS-Document library to 0.9.3

requirements.txt
=> [MASTER] Update osis-doc

requirements.txt
=> OSIS-8237: [OSIS-Document] Fix typo lorsque le lien est expiré

inscription_aux_cours/templates/inscription_aux_cours/blocks/barre_de_progression.html
…our certains formations alors qu'on a des crédits cibles)
=> OSIS-8356: fix côté étudiant de 8347 ( Plus de barre de progression pour certains formations alors qu'on a des crédits cibles)

inscription_aux_cours/templates/inscription_aux_cours/blocks/barre_de_progression.html, inscription_aux_cours/templates/inscription_aux_cours/blocks/barres_de_progression.html
=> OSIS-8356: barres de progression mal réparties en largeur (adaptation comme dans OSIS)

inscription_aux_cours/templates/inscription_aux_cours/blocks/barre_de_progression.html, inscription_aux_cours/templates/inscription_aux_cours/blocks/barres_de_progression.html
Pull request automatique de hotfix/OSIS-8356 vers QA
=> [hotfix/OSIS-8356 => QA] Pas de progression côté étudiant pour les agrégations

inscription_aux_cours/templates/inscription_aux_cours/blocks/barre_de_progression.html, inscription_aux_cours/templates/inscription_aux_cours/blocks/barres_de_progression.html
=> [hotfix/OSIS-8356 => DEV]: Pas de progression côté étudiant pour les agrégations 

inscription_aux_cours/locale/en/LC_MESSAGES/django.po, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/soumettre_proposition.html, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html, inscription_aux_cours/views/cours/recapitulatif.py
=> OSIS-8354: Limite crédits inscrits > 60 devenue >=60 pour les 1ADP et BAMA15

inscription_aux_cours/views/common.py, program_management/services/programme.py
Merge branch 'qa' of github.com:uclouvain/osis-portal-internship into dev
=> [QA] OSIS-7958 exclude phd and formation_phd from enrolment

inscription_aux_cours/views/common.py, program_management/services/programme.py
Pull request automatique de feature/OSIS-7958 vers DEV
=> [feature/OSIS-7958 => DEV] [CAS FILTRE FORMATIONS] exclure les doctorats des formations inscriptibles côté parcours

inscription_aux_cours/forms/activites_aide_reussite/activites.py, inscription_aux_cours/forms/cours/inscription_hors_programme.py, inscription_aux_cours/locale/en/LC_MESSAGES/django.po, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/templates/inscription_aux_cours/activites_aide_reussite/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/blocks/barre_de_progression.html, inscription_aux_cours/templates/inscription_aux_cours/blocks/contact.html, inscription_aux_cours/templates/inscription_aux_cours/blocks/header_formation.html, inscription_aux_cours/templates/inscription_aux_cours/blocks/page_header.html, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/cours_hors_programme.html, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/legende.html, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/proposition_programme_annuel_etudiant.html, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/soumettre_proposition.html, inscription_aux_cours/templates/inscription_aux_cours/cours/desinscrire.html, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html, inscription_aux_cours/templates/inscription_aux_cours/layout.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/modal_confirmation_aucune_inscription.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/recapitulatif.html, inscription_aux_cours/templates/inscription_aux_cours/non_autorisee.html, inscription_aux_cours/templates/inscription_aux_cours/selectionner_formation.html, inscription_aux_cours/templatetags/inscription_aux_cours_extra.py, inscription_aux_cours/views/cours/proposition_programme_annuel.py, inscription_aux_cours/views/cours/soumettre_proposition.py
=> OSIS-7628: changements des versions anglaises dans les écrans d'inscription_aux_cours

inscription_aux_cours/forms/activites_aide_reussite/activites.py, inscription_aux_cours/forms/cours/inscription_hors_programme.py, inscription_aux_cours/locale/en/LC_MESSAGES/django.po, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/templates/inscription_aux_cours/activites_aide_reussite/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/blocks/barre_de_progression.html, inscription_aux_cours/templates/inscription_aux_cours/blocks/contact.html, inscription_aux_cours/templates/inscription_aux_cours/blocks/header_formation.html, inscription_aux_cours/templates/inscription_aux_cours/blocks/page_header.html, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/cours_hors_programme.html, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/legende.html, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/proposition_programme_annuel_etudiant.html, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/soumettre_proposition.html, inscription_aux_cours/templates/inscription_aux_cours/cours/desinscrire.html, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html, inscription_aux_cours/templates/inscription_aux_cours/layout.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/modal_confirmation_aucune_inscription.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/recapitulatif.html, inscription_aux_cours/templates/inscription_aux_cours/non_autorisee.html, inscription_aux_cours/templates/inscription_aux_cours/selectionner_formation.html, inscription_aux_cours/templatetags/inscription_aux_cours_extra.py, inscription_aux_cours/views/cours/proposition_programme_annuel.py, inscription_aux_cours/views/cours/soumettre_proposition.py
Pull request automatique de technical/OSIS-7628 vers DEV
=> [technical/OSIS-7628 => DEV] Traduction anglaise ddd (messages), osis-portal, osis (PDF)

inscription_aux_cours/locale/en/LC_MESSAGES/django.po, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/templates/inscription_aux_cours/blocks/tableau_de_progression.html
=> OSIS-8130: modifications des traductions pour le tableau de progression

dashboard/locale/en/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po, dashboard/views/home.py
=> [technical/OSIS-8418 => DEV]: My composition enrollment --> My annual programme

inscription_aux_cours/static/inscription_aux_cours/css/print_proposition_programme_annuel.css, inscription_aux_cours/templates/inscription_aux_cours/blocks/tableau_de_progression.html, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html
=> OSIS-8130: corrections issues

inscription_aux_cours/templates/inscription_aux_cours/blocks/tableau_de_progression.html
=> Osis 8130: corrections

inscription_aux_cours/templates/inscription_aux_cours/blocks/barres_de_progression.html
=> correction-regression: "|add:1" dans barres_de_progression.html

base/management/commands/check_messages_conflicts.py, inscription_aux_cours/locale/en/LC_MESSAGES/django.po, inscription_aux_cours/locale/fr_BE/LC_MESSAGES/django.po, inscription_aux_cours/templates/inscription_aux_cours/activites_aide_reussite/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/blocks/header_formation.html, inscription_aux_cours/templates/inscription_aux_cours/cours/blocks/proposition_programme_annuel_etudiant.html, inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/formulaire.html, inscription_aux_cours/templates/inscription_aux_cours/mini_formation/recapitulatif.html, inscription_aux_cours/templates/inscription_aux_cours/non_autorisee.html, inscription_aux_cours/templates/inscription_aux_cours/selectionner_formation.html
…es conflits et ajout de la commande de check_messages_conflicts.py
=> [conflits-traductions=>QA]: contextualisation des traductions qui causent des conflits et ajout de la commande de check_messages_conflicts.py

frontoffice/settings/base.py
=> Add missing switches

inscription_aux_cours/views/common.py
Pull request automatique de hotfix/OSIS-8464 vers MASTER
=> [hotfix/OSIS-8464 => MASTER] Page not found pour certaines étudiants > django.core.exceptions.ValidationError: [_Valeur trop grande._]

base/templates/hijack/notification.html
=> [technical/OSIS-8475 => DEV] Adaptaion du template hijack

inscription_aux_cours/forms/cours/demande_particuliere.py
Pull request automatique de hotfix/OSIS-8477 vers MASTER
=> [hotfix/OSIS-8477 => MASTER] Erreur si on saisit un long commentaire >  django.core.exceptions.ValidationError: [_Valeur trop grande._] 

inscription_aux_cours/forms/cours/demande_particuliere.py
Pull request automatique de hotfix/OSIS-8477 vers QA
=> [hotfix/OSIS-8477 => QA] Erreur si on saisit un long commentaire >  django.core.exceptions.ValidationError: [_Valeur trop grande._] 

inscription_aux_cours/forms/cours/demande_particuliere.py
Pull request automatique de hotfix/OSIS-8477 vers DEV
=> [hotfix/OSIS-8477 => DEV] Erreur si on saisit un long commentaire >  django.core.exceptions.ValidationError: [_Valeur trop grande._] 

inscription_aux_cours/templates/inscription_aux_cours/blocks/contact.html
Pull request automatique de hotfix/OSIS-8453 vers QA
=> [hotfix/OSIS-8453 => QA] Régression pour la mise en forme du contact en fac

requirements.txt
=> OSIS-8497 : update reference sdk requirements

inscription_aux_cours/views/cours/mon_pae_valide_jury.py
=> OSIS-8481: Afficher une message Accès refusé si l'étudiant essaie d'accéder à des PDF qui ne le concernent pas

inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html
=> OSIS-8461: Les barres de progression ne sont pas visibles si le PAE est vide

inscription_aux_cours/static/inscription_aux_cours/css/print_proposition_programme_annuel.css, inscription_aux_cours/templates/inscription_aux_cours/cours/recapitulatif.html
=> OSIS-8357: Remove .hide_print class on multiple section

inscription_aux_cours/views/cours/mon_pae_valide_jury.py
Pull request automatique de hotfix/OSIS-8481 vers QA
=> [WIP] [hotfix/OSIS-8481 => QA] Afficher une message Accès refusé si l_étudiant essaie d_accéder à des PDF qui ne le concernent pas

attribution/services/application.py, attribution/templates/attribution_overview.html, dashboard/views/home.py, requirements.txt
=> OSIS-7773: Gestion des permissions via API

inscription_aux_cours/static/inscription_aux_cours/js/inscription_aux_cours.js
=> OSIS 8566 : correction couleur des badges credites et valorisés

requirements.txt
=> Upgrade osis-document to 0.9.7

.env.example, base/templates/server_error.html, base/tests/views/test_common.py, base/views/common.py, frontoffice/settings/base.py
=> OSIS-8575: Adapter la page d'erreur  OSIS pour passage Service Desk

inscription_aux_cours/templates/inscription_aux_cours/blocks/tableau_de_progression.html
=> OSIS-8572: Remove '<' char on progression before 2015-16 tab

.env.example, base/templates/server_error.html, base/tests/views/test_common.py, base/views/common.py, frontoffice/settings/base.py
Pull request automatique de hotfix/OSIS-8575 vers MASTER
=> [hotfix/OSIS-8575 => MASTER] Adapter la page d_erreur OSIS pour le passage du Service Desk sous Confluence/Jira

base/models/signals.py
=> INTERNSHIP-298 assign to internship student group

base/models/signals.py
=> INTERNSHIP-298 temporary disable method not available through sdk yet

base/models/signals.py
=> [To DEV] INTERNSHIP-298 update signals to add/remove to group according to api response

manage.py
=> OpenTelemetry: skip_dep_check for URLLib3Instrumentor

base/models/signals.py
=> OSIS-8610 remove internship students group instead of students group

assessments/views/score_encoding.py, attestation/models/enums/attestation_type.py, attestation/tests/views/test_download.py, attestation/tests/views/test_home.py, attestation/views/download.py, attestation/views/home.py, attribution/forms/application.py, attribution/tests/views/online_application/test_outside_period.py, attribution/tests/views/test_list.py, attribution/views/online_application/delete.py, attribution/views/online_application/outside_period.py, attribution/views/online_application/renew_multiple_application_about_to_expire.py, attribution/views/online_application/send_summary.py, base/forms/base_forms.py, base/models/education_group_type.py, base/models/education_group_year.py, base/models/entity_version.py, base/models/enums/education_group_categories.py, base/models/enums/learning_container_type.py, base/models/person.py, base/models/signals.py, dashboard/views/home.py, performance/models/enums/session_month.py, performance/tests/views/test_main.py, requirements.txt
Reverts uclouvain/osis-portal#3227
=> Revert "OSIS-8616 :Update django requirements"

requirements.txt
=> Update OSIS-Document version

assessments/views/score_encoding.py, attestation/models/enums/attestation_type.py, attestation/tests/views/test_download.py, attestation/tests/views/test_home.py, attestation/views/download.py, attestation/views/home.py, attribution/forms/application.py, attribution/tests/views/online_application/test_outside_period.py, attribution/tests/views/test_list.py, attribution/views/online_application/delete.py, attribution/views/online_application/outside_period.py, attribution/views/online_application/renew_multiple_application_about_to_expire.py, attribution/views/online_application/send_summary.py, base/forms/base_forms.py, base/models/education_group_type.py, base/models/education_group_year.py, base/models/entity_version.py, base/models/enums/education_group_categories.py, base/models/enums/learning_container_type.py, base/models/person.py, base/models/signals.py, dashboard/views/home.py, performance/models/enums/session_month.py, performance/tests/views/test_main.py, requirements.txt
Reverts uclouvain/osis-portal#3229
=> OSIS-8616 :Update django requirements

frontoffice/settings/local.py
=> [QA] Enable admission

frontoffice/settings/local.py
=> Release admission: uncomment admission in local.py

requirements.txt
=> Fix OS-658: Permettre à l'utilisateur de retravailler la photo ID

base/templates/layout.html
=> [admission-os-672] Allow the customization of the footer in the layout

base/models/signals.py
=> [hotfix/OSIS-8700 => MASTER] Ne pas mettre à jour "Person" si le fgs ne commence pas par 8

frontoffice/settings/local.py
=> Release TEST

frontoffice/settings/osis_sdk/utils.py, frontoffice/tests/settings/osis_sdk/test_utils.py
=> [master] Fix OS-700: Api exception handling error

frontoffice/settings/osis_sdk/utils.py, frontoffice/tests/settings/osis_sdk/test_utils.py
=> Fix OS-700: Api exception handling error

frontoffice/settings/osis_sdk/utils.py
=> Release 5.13.2

requirements.txt
=> Release 5.13.3

requirements.txt
=> [OS-714 -> QA] Upgrade osis-document to fix the update of the same document several times

requirements.txt
=> [OS-714 -> TEST] Upgrade osis-document to fix the update of the same document several times

requirements.txt
=> [OS-714 -> DEV] Upgrade osis-document to fix the update of the same document several times

requirements.txt
=> [OS-714 -> PROD] Upgrade osis-document to fix the update of the same document several times

requirements.txt
=> OSIS-8809: Update OSIS-Reference SDK package

performance/templates/performance_result.html
=> OSIS 7672 : modification des flags allegement150 et reorientation en string

performance/templates/performance_result.html
=> OSIS 7672 : correction test allegement150 = oui

performance/templates/performance_result.html, performance/views/main.py
=> OSIS 7672 : correction get flags allegement150 et reorientation

attribution/forms/application.py, base/models/entity_version.py
=> Osis 8887: Permettre de rechercher sur des facultés Saint-Louis

attribution/forms/application.py, base/models/entity_version.py
Pull request automatique de hotfix/OSIS-8887 vers MASTER
=> [hotfix/OSIS-8887 => MASTER] [Candidature en ligne] Permettre la recherche sur les facultés Saint-Louis

attribution/forms/application.py, base/models/entity_version.py
=> Release 5.15.5

base/models/signals.py
Pull request automatique de hotfix/OSIS-8896 vers MASTER
=> [hotfix/OSIS-8896 => MASTER] Les personnes ne sont pas créées à la connexion quand la date a un format non accepté

requirements.txt
=> [technical/OSIS-8889 -> DEV] Upgrade OSIS-Document to 0.10.0

requirements.txt
=> [technical/OSIS-8889 => TEST] Update OSIS-Document to 0.10.0 version 

requirements.txt
=> [Hotfix/OS-786 => RC-5.15.9] : Longueur des noms de documents

requirements.txt
=> [hotfix/OS-786 ==> DEV] Longueur des noms de documents

inscription_evaluation/locale/en/LC_MESSAGES/django.po, inscription_evaluation/locale/fr_BE/LC_MESSAGES/django.po, inscription_evaluation/templates/inscription_evaluation/formulaire_inscription.html, requirements.txt
=> OSIS-8623 issue 1

inscription_evaluation/templates/inscription_evaluation/recapitulatif.html
=> OSIS-8658 corrections issues 1 + 2

inscription_evaluation/locale/en/LC_MESSAGES/django.po, inscription_evaluation/locale/fr_BE/LC_MESSAGES/django.po, inscription_evaluation/templates/inscription_evaluation/formulaire_inscription.html, inscription_evaluation/templates/inscription_evaluation/ue/colonne_session_formulaire.html, inscription_evaluation/templatetags/affichage_note_justification.py, requirements.txt
=> OSIS-8629 correction afficage justification + UE credite

inscription_evaluation/templates/inscription_evaluation/recapitulatif.html, inscription_evaluation/templates/inscription_evaluation/ue/type_inscription.html
=> OSIS-8219 gestion deuxieme reinscription badge

inscription_evaluation/templates/inscription_evaluation/formulaire_inscription.html, inscription_evaluation/templates/inscription_evaluation/ue/colonne_session_formulaire.html, inscription_evaluation/templates/inscription_evaluation/ue/type_inscription.html, requirements.txt
=> feature/OSIS-7954: corrections-affichage badges + affichage test dispensatoire

inscription_evaluation/locale/en/LC_MESSAGES/django.po, inscription_evaluation/locale/fr_BE/LC_MESSAGES/django.po, inscription_evaluation/views/selectionner_programme.py
=> feature/OSIS-7954: message info pour 404

frontoffice/settings/local.py, inscription_evaluation/locale/en/LC_MESSAGES/django.po, inscription_evaluation/locale/fr_BE/LC_MESSAGES/django.po, inscription_evaluation/templates/inscription_evaluation/blocks/contact.html, inscription_evaluation/templates/inscription_evaluation/blocks/legende.html, inscription_evaluation/templates/inscription_evaluation/formulaire_inscription.html, inscription_evaluation/templates/inscription_evaluation/recapitulatif.html, inscription_evaluation/templates/inscription_evaluation/ue/colonne_session_formulaire.html, inscription_evaluation/templatetags/affichage_note_justification.py, requirements.txt
=> OSIS-9004: corrections démo

requirements.txt
=> [OS-865 => master] nom de fichier trop long dupliqué

inscription_evaluation/templates/inscription_evaluation/selectionner_programme.html
=> OSIS-9004: correction issue 1

inscription_evaluation/services/annee_academique.py, inscription_evaluation/views/selectionner_programme.py
=> OSIS-7653 issue 5

inscription_evaluation/views/recapitulatif.py
=> OSIS-8036 soumettre formulaire etudiant

inscription_evaluation/locale/en/LC_MESSAGES/django.po, inscription_evaluation/locale/fr_BE/LC_MESSAGES/django.po, inscription_evaluation/templates/inscription_evaluation/blocks/contact.html, inscription_evaluation/templates/inscription_evaluation/blocks/legende.html, inscription_evaluation/templates/inscription_evaluation/formulaire_inscription.html, inscription_evaluation/templates/inscription_evaluation/recapitulatif.html, inscription_evaluation/templates/inscription_evaluation/selectionner_programme.html, inscription_evaluation/templates/inscription_evaluation/ue/colonne_session_formulaire.html, inscription_evaluation/templatetags/affichage_note_justification.py, requirements.txt
Pull request automatique de technical/OSIS-9004 vers DEV
=> [technical/OSIS-9004 => DEV] Retour réunion métier du 26/02 > ajustement côté étudiant et gestionnaire

inscription_evaluation/services/formulaire_inscription.py, inscription_evaluation/views/formulaire_inscription.py, inscription_evaluation/views/recapitulatif.py, requirements.txt
=> OSIS-8035 issues 1 + 2

inscription_evaluation/services/formulaire_inscription.py, inscription_evaluation/services/recapitulatif.py, inscription_evaluation/templates/inscription_evaluation/selectionner_programme.html, inscription_evaluation/urls.py, inscription_evaluation/views/common.py, inscription_evaluation/views/formulaire_inscription.py, inscription_evaluation/views/recapitulatif.py, requirements.txt
=> OSIS-9100: refactor code_programme --> sigle_formation

inscription_evaluation/services/formulaire_inscription.py, inscription_evaluation/services/recapitulatif.py, inscription_evaluation/templates/inscription_evaluation/selectionner_programme.html, inscription_evaluation/urls.py, inscription_evaluation/views/common.py, inscription_evaluation/views/formulaire_inscription.py, inscription_evaluation/views/recapitulatif.py, requirements.txt
Pull request automatique de technical/OSIS-9100 vers DEV
=> [WIP] [technical/OSIS-9100 => DEV] Ajustements suite à la réunion métier 25/03

inscription_evaluation/services/formulaire_inscription.py, inscription_evaluation/services/recapitulatif.py, inscription_evaluation/urls.py
=> [technical/OSIS-9100=>DEV]: convert url pour les slashs

inscription_evaluation/templates/inscription_evaluation/recapitulatif.html
=> correction-refactor: oublie de changement du code programme par sigle de formation dans les urls

inscription_evaluation/templates/inscription_evaluation/blocks/message_taille_ecran.html, inscription_evaluation/templates/inscription_evaluation/formulaire_inscription.html, inscription_evaluation/templates/inscription_evaluation/recapitulatif.html, inscription_evaluation/templates/inscription_evaluation/selectionner_programme.html
=> OSIS-9087: message avertissement pour écran trop petit + tableau responsive

inscription_evaluation/templates/inscription_evaluation/blocks/message_taille_ecran.html, inscription_evaluation/templates/inscription_evaluation/formulaire_inscription.html, inscription_evaluation/templates/inscription_evaluation/recapitulatif.html, inscription_evaluation/templates/inscription_evaluation/selectionner_programme.html
Pull request automatique de technical/OSIS-9087 vers DEV
=> [WIP] [technical/OSIS-9087 => DEV] Ajuster le rendu sur smartphone + ajouter le message d_avertissement concernant la taille de l_écran

assessments/views/score_encoding.py, attestation/tests/views/test_administration.py, attestation/tests/views/test_download.py, attestation/tests/views/test_home.py, attribution/tests/business/test_xls_students_by_learning_unit.py, attribution/tests/views/online_application/test_create.py, attribution/tests/views/online_application/test_delete.py, attribution/tests/views/online_application/test_overview.py, attribution/tests/views/online_application/test_renew_multiple_application_about_to_expire.py, attribution/tests/views/online_application/test_search_vacant_courses.py, attribution/tests/views/online_application/test_select_tutor.py, attribution/tests/views/online_application/test_send_summary.py, attribution/tests/views/online_application/test_update.py, attribution/tests/views/test_list.py, attribution/tests/views/test_select_tutor_for_attribution.py, attribution/tests/views/test_tutor_charge.py, base/services/utils.py, base/tests/views/test_administration.py, base/tests/views/test_my_osis.py, base/views/api.py, dashboard/tests/views/student/test_my_personal_information.py, exam_enrollment/tests/views/test_offer_choice.py, frontoffice/settings/base.py, frontoffice/settings/osis_sdk/utils.py, performance/tests/views/test_main.py, performance/tests/views/test_performance_home.py, requirements.txt
=> Update requirements and remove DRF

base/urls.py, performance/queue/student_performance.py, performance/tests/models/test_student_performance.py, performance/tests/queue/test_queue_student_performance.py
=> Fix warnings in tests + allow to get status of osis-portal

inscription_evaluation/services/formulaire_inscription.py, inscription_evaluation/templates/inscription_evaluation/blocks/header_formation.html, inscription_evaluation/templates/inscription_evaluation/formulaire_inscription.html, inscription_evaluation/templates/inscription_evaluation/recapitulatif.html, inscription_evaluation/templates/inscription_evaluation/selectionner_programme.html, inscription_evaluation/views/common.py, inscription_evaluation/views/recapitulatif.py, requirements.txt
=> correction-sigle: sigle_formation != sigle_complet_version_formation

inscription_evaluation/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-9195: issue 1

requirements.txt
=> OSIS-9166 Incrémenter la version du SKD Education Group

inscription_evaluation/templates/inscription_evaluation/formulaire_inscription.html, inscription_evaluation/views/formulaire_inscription.py, requirements.txt
=> OSIS-9215: messages d'avertissement

inscription_evaluation/templates/inscription_evaluation/blocks/header_formation.html, inscription_evaluation/templates/inscription_evaluation/formulaire_inscription.html, inscription_evaluation/templates/inscription_evaluation/recapitulatif.html, inscription_evaluation/templates/inscription_evaluation/selectionner_programme.html, inscription_evaluation/views/formulaire_inscription.py, requirements.txt
=> OSIS-8634: intitule formation, contexte et UE en anglais également

inscription_evaluation/services/pdf_demande_inscription.py, inscription_evaluation/views/fichiers/ma_demande_inscription.py
=> OSIS-8634: redirection vers le PDF lors du clique dans le mail

inscription_evaluation/services/pdf_validation_inscription.py, inscription_evaluation/urls.py, inscription_evaluation/views/fichiers/ma_demande_inscription.py, inscription_evaluation/views/fichiers/ma_validation_inscription.py, requirements.txt
=> OSIS-8069: redirection vers le PDF lors du clique dans le mail

inscription_evaluation/services/pdf_demande_inscription.py, inscription_evaluation/services/pdf_validation_inscription.py, inscription_evaluation/urls.py, inscription_evaluation/views/fichiers/ma_demande_inscription.py, inscription_evaluation/views/fichiers/ma_validation_inscription.py
=> OSIS-8069: uuid pour récupérer le bon PDF

base/utils/eval.py
=> Add base.utils.eval.eval_bool

attribution/locale/fr_BE/LC_MESSAGES/django.po, dashboard/locale/fr_BE/LC_MESSAGES/django.po
=> OSIS-8994: examen --> evaluation

inscription_evaluation/locale/en/LC_MESSAGES/django.po, inscription_evaluation/locale/fr_BE/LC_MESSAGES/django.po, inscription_evaluation/templates/inscription_evaluation/blocks/legende.html, inscription_evaluation/templatetags/affichage_note_justification.py
=> OSIS-9002 issues 2 et 3

frontoffice/settings/local.py
=> corr-dev: commentaire incorrect

inscription_evaluation/locale/en/LC_MESSAGES/django.po, inscription_evaluation/locale/fr_BE/LC_MESSAGES/django.po, inscription_evaluation/templates/inscription_evaluation/blocks/legende.html
=> OSIS-8879: changement EN évals réussies/ratés

inscription_aux_cours/services/pdf_pae_valide_jury.py, inscription_aux_cours/services/pdf_proposition_pae.py, inscription_aux_cours/urls.py, inscription_aux_cours/views/cours/ma_proposition_de_pae.py, inscription_aux_cours/views/cours/mon_pae_valide_jury.py, requirements.txt
=> OSIS-9340: refactor permission + adaptation récupération PDF par uuid

frontoffice/queue/queue_listener.py
=> Correction queue rpc pour pika 3.1.2 (Merge to dev)

attestation/queues/student_attestation_status.py, frontoffice/queue/queue_listener.py
=> Correction queues pour pika 1.3.2 et python 3.11 (Merge to QA)

inscription_aux_cours/services/pdf_pae_valide_jury.py, inscription_aux_cours/services/pdf_proposition_pae.py, inscription_aux_cours/urls.py, inscription_aux_cours/views/cours/ma_proposition_de_pae.py, inscription_aux_cours/views/cours/mon_pae_valide_jury.py, requirements.txt
Pull request automatique de technical/OSIS-9340 vers DEV
=> [technical/OSIS-9340 => DEV] [PDF PROPOSITION-VALIDATION] Adapter la logique pour accéder au PDF sur studies pour ajouter le uuid dans l_URL

manage_submodules.py
=> Osis correction manage submodule.py (Merge to DEV)

manage_submodules.py
=> Ajout strip pour choix branche adéquate des sous-module si pas dev (Merge to QA)

frontoffice/settings/base.py
=>  MAJ logger pour assync (Merge to QA)

base/models/entity_version.py, frontoffice/settings/base.py
=> [ hotfix/OSIS-9444 => MASTER] Maj des imorts de iterable pour collection

frontoffice/settings/base.py
=> Ajout logger assync

dashboard/views/home.py
…nnement rubrique Mon inscription aux évaluations
=> OSIS-8943: [CAS ACCESS] désactiver l'ancien module et repositionner le nouveau

requirements.txt
Référence Jira : OSIS-9023
https://uclouvain.atlassian.net/browse/OSIS-9023
=> Mise à jour du module osis-notification en 0.1.5

dashboard/views/home.py, requirements.txt
=> [TO QA] Release 6.1

dashboard/views/home.py, requirements.txt
=> [TO TEST] Release 6.1
